Repository vtex/faststore, pull requests merged in 2021-11, with the labels that each got.

#1013 fix: Fix FastStore UI link in README files
  README.md
  themes/theme-b2c-tailwind/README.md
Labels: documentation

#1022 fix: Filter collection slugs in api
  packages/api/package.json
  packages/api/src/platforms/vtex/resolvers/collection.ts
  packages/api/src/platforms/vtex/resolvers/query.ts
  packages/api/src/platforms/vtex/utils/slugify.ts
  yarn.lock
Labels: store-api

#1036 Chore: Adds accessibility addon to storybook
  packages/ui/.storybook/main.js
  packages/ui/package.json
  yarn.lock
Labels: enhancement, store-ui
