Repository vtex/faststore, pull requests merged in 2021-12, with the labels that each got.

#1038 chore: Add accessibility references at component docs
  docs/components-architecture.md
Labels: documentation

#1051 refactor(sdk): Search serialization
  packages/sdk/src/search/Provider.tsx
  packages/sdk/src/search/serializer.ts
  packages/sdk/src/search/useInfiniteSearchState.ts
  packages/sdk/src/search/useSearchState.ts
  packages/sdk/test/search/Provider.test.tsx
  packages/sdk/test/search/serializer.test.ts
  packages/sdk/test/search/usePagination.test.tsx
Labels: enhancement, store-sdk

#1039 Feat: Add automation script to generate component
  CONTRIBUTING.MD
  generators/plopfile.ts
  generators/templates/Component.tsx.hbs
  generators/templates/exportToIndex.hbs
  generators/templates/index.tsx.hbs
  generators/templates/stories.mdx.hbs
  generators/templates/stories.tsx.hbs
  generators/templates/style.css.hbs
  generators/templates/test.tsx.hbs
  package.json
  packages/ui/src/index.ts
  yarn.lock
Labels: enhancement

#1053 chore(ui): Upgrade Storybook from 6.3 to 6.4
  packages/ui/.storybook/main.js
  packages/ui/package.json
  yarn.lock
Labels: dependencies

#1020 feat(store-ui): Alert molecule
  packages/ui/src/index.ts
  packages/ui/src/molecules/Alert/Alert.test.tsx
  packages/ui/src/molecules/Alert/Alert.tsx
  packages/ui/src/molecules/Alert/index.ts
  packages/ui/src/molecules/Alert/stories/Alert.mdx
  packages/ui/src/molecules/Alert/stories/Alert.stories.tsx
  themes/theme-b2c-tailwind/src/molecules/alert.css
  themes/theme-b2c-tailwind/src/molecules/index.css
Labels: store-ui, ui-molecule

#1024 feat(ui): PaymentMethods Component
  lerna.json
  packages/ui/src/index.ts
  packages/ui/src/molecules/PaymentMethods/PaymentMethods.test.tsx
  packages/ui/src/molecules/PaymentMethods/PaymentMethods.tsx
  packages/ui/src/molecules/PaymentMethods/index.tsx
  packages/ui/src/molecules/PaymentMethods/stories/PaymentMethods.mdx
  packages/ui/src/molecules/PaymentMethods/stories/PaymentMethods.stories.tsx
  packages/ui/src/molecules/PaymentMethods/stories/assets/Icons.tsx
  themes/theme-b2c-tailwind/src/molecules/index.css
  themes/theme-b2c-tailwind/src/molecules/payment-methods.css
Labels: store-ui, ui-molecule

#1048 feat(store-ui): Banner component
  packages/ui/src/index.ts
  packages/ui/src/molecules/Banner/Banner.test.tsx
  packages/ui/src/molecules/Banner/Banner.tsx
  packages/ui/src/molecules/Banner/BannerContent.tsx
  packages/ui/src/molecules/Banner/BannerImage.tsx
  packages/ui/src/molecules/Banner/BannerLink.tsx
  packages/ui/src/molecules/Banner/index.ts
  packages/ui/src/molecules/Banner/stories/Banner.mdx
  packages/ui/src/molecules/Banner/stories/Banner.stories.tsx
  themes/theme-b2c-tailwind/src/molecules/accordion.css
  themes/theme-b2c-tailwind/src/molecules/banner.css
  themes/theme-b2c-tailwind/src/molecules/index.css
Labels: store-ui, ui-molecule

#1062 chore: Use b2c theme on docs
  docs/docs/reference/ui/atoms/Badge.mdx
  docs/docs/reference/ui/atoms/Button.mdx
  docs/docs/reference/ui/atoms/Input.mdx
  docs/docs/reference/ui/atoms/Label.mdx
  docs/docs/reference/ui/atoms/Overlay.mdx
  docs/docs/reference/ui/atoms/Popover.mdx
  docs/docs/reference/ui/atoms/TextArea.mdx
  docs/docs/reference/ui/molecules/Modal.mdx
  docs/docs/tutorials/gatsby/05 - Using components.md
  docs/package.json
  docs/src/theme/Playground/index.jsx
  docs/src/theme/ReactLiveScope/index.tsx
  docs/src/theme/ReactLiveScope/styles.css
  themes/theme-b2c-tailwind/src/atoms/overlay.css
  themes/theme-b2c-tailwind/src/atoms/textarea.css
  themes/theme-b2c-tailwind/src/molecules/modal.css
Labels: documentation, enhancement

#1063 docs: Add missing components
  docs/docs/reference/ui/molecules/Breadcrumb.mdx
  docs/docs/reference/ui/molecules/LoadingButton.mdx
  docs/docs/reference/ui/molecules/PriceRange.mdx
  docs/docs/reference/ui/molecules/RadioGroup.mdx
  packages/ui/src/index.ts
  packages/ui/src/molecules/RadioGroup/RadioGroup.test.tsx
  packages/ui/src/molecules/RadioGroup/index.tsx
  themes/theme-b2c-tailwind/src/molecules/breadcrumb.css
Labels: documentation

#1066 docs: update quickstart
  docs/docs/quickstart.md
  packages/api/README.md
  packages/sdk/README.md
  packages/ui/README.md
Labels: documentation

#1060 docs: Upgrade readme
  README.md
Labels: documentation

#1061 docs: Move docs
  docs/docusaurus.config.js
  packages/api/README.md
  packages/sdk/README.md
  packages/ui/README.md
Labels: documentation

#1070 feat: Automatic docs from UI
  docs/docs/reference/ui/atoms/Badge.mdx
  docs/docs/reference/ui/atoms/Button.mdx
  docs/docs/reference/ui/atoms/Checkbox.mdx
  docs/docs/reference/ui/atoms/Icon.mdx
  docs/docs/reference/ui/atoms/Input.mdx
  docs/docs/reference/ui/atoms/Label.mdx
  docs/docs/reference/ui/atoms/List.mdx
  docs/docs/reference/ui/atoms/Overlay.mdx
  docs/docs/reference/ui/atoms/Popover.mdx
  docs/docs/reference/ui/atoms/Price.mdx
  docs/docs/reference/ui/atoms/Radio.mdx
  docs/docs/reference/ui/atoms/Select.mdx
  docs/docs/reference/ui/atoms/Skeleton.mdx
  docs/docs/reference/ui/atoms/Slider.mdx
  docs/docs/reference/ui/atoms/Spinner.mdx
  docs/docs/reference/ui/atoms/TextArea.mdx
  docs/docs/reference/ui/molecules/Accordion.mdx
  docs/docs/reference/ui/molecules/Breadcrumb.mdx
  docs/docs/reference/ui/molecules/Bullets.mdx
  docs/docs/reference/ui/molecules/Carousel.mdx
  docs/docs/reference/ui/molecules/Form.mdx
  docs/docs/reference/ui/molecules/IconButton.mdx
  docs/docs/reference/ui/molecules/LoadingButton.mdx
  docs/docs/reference/ui/molecules/Modal.mdx
  docs/docs/reference/ui/molecules/PriceRange.mdx
  docs/docs/reference/ui/molecules/RadioGroup.mdx
  docs/docs/reference/ui/molecules/SearchInput.mdx
  docs/docs/reference/ui/molecules/Table.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/PropsComponent/PropsComponent.tsx
  docs/src/components/PropsSection/PropsSection.jsx
  docs/src/components/PropsSection/PropsSection.module.css
  packages/ui/src/atoms/List/List.test.tsx
  packages/ui/src/atoms/List/List.tsx
  packages/ui/src/atoms/List/stories/List.mdx
  packages/ui/src/atoms/List/stories/List.stories.tsx
  yarn.lock
Labels: documentation, enhancement

#1068 docs: FAQ
  docs/src/components/FaqQuestion/FaqQuestion.jsx
  docs/src/pages/sections/FaqPage/FaqPage.js
Labels: documentation

#1071 docs: Create Starters section
  docs/docusaurus.config.js
  docs/src/components/StarterComponent/StarterComponent.module.css
  docs/src/components/StarterComponent/StarterComponent.tsx
  docs/src/pages/sections/StarterComponentPage/StarterComponentPage.module.css
  docs/src/pages/sections/StarterComponentPage/StarterComponentPage.tsx
  docs/src/pages/sections/StarterPage/StarterPage.js
  docs/src/pages/sections/StarterPage/StarterPage.module.css
  docs/src/pages/starters.js
  docs/src/pages/starters/base.js
  docs/static/data/starters.json
  docs/static/img/base-starter.png
Labels: documentation

#1075 docs: Algolia to faststore.dev
  docs/docusaurus.config.js
Labels: enhancement

#1077 chore(ui): Fix a circular dependency
  packages/ui/src/molecules/RadioGroup/RadioOption.tsx
Labels: dependencies

#1076 docs: Add Alert, Banner and PaymentMethods docs
  docs/docs/reference/ui/molecules/Alert.mdx
  docs/docs/reference/ui/molecules/Banner.mdx
  docs/docs/reference/ui/molecules/PaymentMethods.mdx
  docs/src/theme/ReactLiveScope/index.tsx
Labels: documentation

#1079 feat(ui): Card component
  packages/ui/src/index.ts
  packages/ui/src/organisms/Card/Card.test.tsx
  packages/ui/src/organisms/Card/Card.tsx
  packages/ui/src/organisms/Card/CardActions.tsx
  packages/ui/src/organisms/Card/CardContent.tsx
  packages/ui/src/organisms/Card/CardImage.tsx
  packages/ui/src/organisms/Card/index.tsx
  packages/ui/src/organisms/Card/stories/Card.mdx
  packages/ui/src/organisms/Card/stories/Card.stories.tsx
  themes/theme-b2c-tailwind/src/index.css
  themes/theme-b2c-tailwind/src/organisms/card.css
  themes/theme-b2c-tailwind/src/organisms/index.css
Labels: store-ui, ui-organism

#1067 feat(ui): Link atom
  packages/ui/src/atoms/Link/Link.test.tsx
  packages/ui/src/atoms/Link/Link.tsx
  packages/ui/src/atoms/Link/index.tsx
  packages/ui/src/atoms/Link/stories/Link.mdx
  packages/ui/src/atoms/Link/stories/Link.stories.tsx
  packages/ui/src/index.ts
  packages/ui/src/typings/PolymorphicGenerics.ts
  packages/ui/src/typings/index.ts
  themes/theme-b2c-tailwind/src/atoms/index.css
  themes/theme-b2c-tailwind/src/atoms/link.css
Labels: store-ui, ui-atom

#1064 feat(ui): Incentive atom
  packages/ui/src/atoms/Incentive/Incentive.test.tsx
  packages/ui/src/atoms/Incentive/Incentive.tsx
  packages/ui/src/atoms/Incentive/index.tsx
  packages/ui/src/atoms/Incentive/stories/Incentive.mdx
  packages/ui/src/atoms/Incentive/stories/Incentive.stories.tsx
  packages/ui/src/atoms/Incentive/stories/assets/Icons.tsx
  packages/ui/src/index.ts
  themes/theme-b2c-tailwind/src/atoms/incentive.css
  themes/theme-b2c-tailwind/src/atoms/index.css
Labels: store-ui, ui-atom

#1084 docs: Update Faststore and FastStore UI overview docs
  docs/docs/how-to-guides/contributing/component.md
  docs/docs/how-to-guides/contributing/design-principles.md
  docs/docs/index.md
  docs/docs/reference/Usage.md
  docs/docs/reference/api/faststore-api.md
  docs/docs/reference/faststore.md
  docs/docs/reference/project-structure.md
  docs/docs/reference/sdk/faststore-sdk.md
  docs/docs/reference/ui/Overview.md
  docs/docs/reference/ui/atoms/Input.mdx
  docs/docs/reference/ui/atoms/Price.mdx
  docs/docs/reference/ui/atoms/TextArea.mdx
  docs/docs/reference/ui/faststore-ui.md
  docs/docs/reference/ui/get-started-faststore-ui.md
  docs/docs/reference/ui/molecules/Banner.mdx
  docs/docs/reference/ui/organisms/Card.mdx
  docs/docs/tutorials/gatsby/05 - Using components.md
  docs/docs/tutorials/overview.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/FastStorePackages/FastStorePackages.module.css
  docs/src/components/FastStorePackages/FastStorePackages.tsx
  docs/src/components/IconGrid/IconGrid.jsx
  docs/src/components/IconGrid/IconGrid.module.css
  docs/src/components/PropsComponent/PropsComponent.module.css
  docs/src/pages/sections/FaqPage/FaqPage.js
  docs/src/theme/Playground/styles.module.css
  docs/static/img/faststore-api.png
  docs/static/img/faststore-sdk.png
  docs/static/img/faststore-ui.png
  docs/static/img/github.png
  docs/static/img/youtube.png
Labels: documentation

#1091 Chore: Uses section instead of aria role on CardContent component
  packages/ui/src/organisms/Card/CardContent.tsx
Labels: enhancement
