Repository vtex/faststore, pull requests merged in 2022-07, with the labels that each got.

#1387 docs: Add FastStore - June RN
  apps/docs/blog/2022-07-01-faststore.md
  apps/docs/static/data/releases.json
  lerna.json
Labels: documentation

#1389 docs: Add Base Store June RN
  apps/docs/blog/2022-06-03-basestore.md
  apps/docs/blog/2022-07-01-basestore.md
  apps/docs/static/data/releases.json
Labels: documentation

#1394 fix: @faststore/graphql-utils
  packages/api/src/__generated__/schema.ts
  packages/graphql-utils/tsconfig.json
  packages/lighthouse/tsconfig.json
Labels: bug

#1399 feat: Add priceCurrency to Offer
  packages/api/mocks/salesChannel.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/clients/commerce/types/SalesChannel.ts
  packages/api/src/platforms/vtex/loaders/index.ts
  packages/api/src/platforms/vtex/loaders/salesChannel.ts
  packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts
  packages/api/src/platforms/vtex/resolvers/offer.ts
  packages/api/test/__snapshots__/mutations.test.ts.snap
  packages/api/test/__snapshots__/queries.test.ts.snap
  packages/api/test/mutations.test.ts
  packages/api/test/queries.test.ts
Labels: enhancement, store-api

#1401 Create Widgets.md
  apps/docs/docs/how-to-guides/cms/vtex-headless-cms/Widgets.md
Labels: documentation

#1390 Docs/guide graphiql
  apps/docs/docs/how-to-guides/faststore-api/using-graphiql-to-explore-the-faststore-api.mdx
Labels: documentation

#1404 fix: `PriceRange` track position
  packages/ui/src/molecules/PriceRange/PriceRange.tsx
Labels: bug

#1408 docs: Add RN about new env var
  apps/docs/blog/2022-06-02-webops.md
  apps/docs/blog/2022-07-19-webops.md
  apps/docs/docs/reference/api/mutations/cart.mdx
  apps/docs/docs/reference/api/mutations/session.mdx
  apps/docs/docs/reference/api/queries/allCollections.mdx
  apps/docs/docs/reference/api/queries/allProducts.mdx
  apps/docs/docs/reference/api/queries/collection.mdx
  apps/docs/docs/reference/api/queries/product.mdx
  apps/docs/docs/reference/api/queries/search.mdx
  apps/docs/src/components/DocFooter/DocFooter.js
  apps/docs/src/components/FastStore/FastStore.js
  apps/docs/static/data/doc-update.json
  apps/docs/static/data/releases.json
Labels: documentation

#1419 docs: fix analytics docs errors
  apps/docs/docs/conceptual-guides/analytics-on-faststore.md
  apps/docs/docs/reference/sdk/analytics/how-to-send-custom-events.md
  apps/docs/docs/reference/sdk/analytics/useAnalyticsEvent.md
Labels: documentation

#1418 feat: Add ProductTitle Molecule
  packages/styles/src/molecules/index.css
  packages/styles/src/molecules/product-title.css
  packages/ui/src/index.ts
  packages/ui/src/molecules/ProductTitle/ProductTitle.tsx
  packages/ui/src/molecules/ProductTitle/index.tsx
  packages/ui/src/molecules/ProductTitle/stories/ProductTitle.mdx
  packages/ui/src/molecules/ProductTitle/stories/ProductTitle.stories.tsx
Labels: store-ui, ui-molecule
