Repository vtex/faststore, pull requests merged in 2022-05, with the labels that each got.

#1258 Docs/blog/web ops cms preview authentication enabled by default
  docs/blog/2022-05-02-cms.md
  docs/docs/how-to-guides/cms/vtex-headless-cms/Enabling private CMS previews.md
  docs/static/data/releases.json
Labels: documentation

#1263 docs: remove Tailwind installation from docs
  docs/docs/reference/ui/get-started-faststore-ui.md
Labels: documentation

#1268 docs: fix docusaurus build
  docs/docusaurus.config.js
  docs/vercel.json
Labels: documentation

#1270 fix: missing additionalProperties
  packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts
  packages/api/src/platforms/vtex/resolvers/product.ts
  packages/api/src/platforms/vtex/resolvers/productGroup.ts
Labels: bug, store-api

#1271 fix: Release workflow
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: bug

#1275 docs: Release notes april
  docs/blog/2022-05-06-basestore.md
  docs/blog/2022-05-06-faststore.md
  docs/static/data/releases.json
Labels: documentation

#1277 docs: updated lerna.json due to Release Notes
  lerna.json
Labels: documentation

#1279 docs: Add redirect loop troubleshooting guide
  docs/docs/v0/troubleshooting.md
Labels: documentation

#1282 fix: Offer availability
  packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts
  packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts
  packages/api/src/platforms/vtex/resolvers/offer.ts
  packages/api/src/platforms/vtex/resolvers/product.ts
  packages/api/src/platforms/vtex/utils/enhanceCommercialOffer.ts
  packages/api/src/platforms/vtex/utils/productStock.ts
  packages/api/test/__snapshots__/queries.test.ts.snap
  packages/api/test/vtex.aggregateOffer.test.ts
Labels: bug, store-api

#1285 docs: update starter pages metadata
  docs/src/pages/starters.js
  docs/src/pages/starters/base.js
  docs/src/pages/starters/beauty.js
  docs/src/pages/starters/cms-base.js
  docs/src/pages/starters/toy.js
  docs/static/img/faststore_thumbnail.png
Labels: documentation

#1286 Webops release note
  docs/blog/2022-05-11-webops.md
  docs/static/data/releases.json
Labels: documentation

#1227 docs: update the badge documentation at faststore.dev
  docs/docs/reference/ui/atoms/Badge.mdx
Labels: documentation

#1287 Fix: Components styles and update data attributes
  docs/docs/reference/ui/atoms/Slider.mdx
  docs/docs/reference/ui/molecules/Accordion.mdx
  docs/docs/reference/ui/molecules/Banner.mdx
  docs/docs/reference/ui/molecules/PriceRange.mdx
  docs/docs/reference/ui/molecules/Table.mdx
  packages/ui/src/molecules/Table/Table.test.tsx
  themes/theme-b2c-tailwind/src/atoms/slider.css
  themes/theme-b2c-tailwind/src/molecules/accordion.css
  themes/theme-b2c-tailwind/src/molecules/banner.css
  themes/theme-b2c-tailwind/src/molecules/price-range.css
  themes/theme-b2c-tailwind/src/molecules/table.css
Labels: documentation

#1290 docs: Created template files for the FastStore UI components
  docs/docs/templates/ui-components.md
Labels: documentation

#1300 docs: review release notes + add guide template
  docs/blog/2022-05-11-webops.md
  docs/docs/reference/ui/atoms/Badge.mdx
  docs/docs/templates/how-to-guide-template.md
  docs/static/data/releases.json
Labels: documentation

#1306 fix: Breadcrumb broken links
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/resolvers/product.ts
Labels: bug, store-api

#1305 Create 2022-05-18-faststore.md
  docs/blog/2022-05-18-faststore.md
  docs/static/data/releases.json
Labels: documentation

#1308 docs: Update docs sidebar
  docs/blog/2022-04-01-basestore.md
  docs/blog/2022-04-29-basestore.md
  docs/blog/2022-05-06-basestore.md
  docs/docs/faq.mdx
  docs/docs/how-to-guides/local-development/troubleshooting-problems-in-faststore.md
  docs/docs/quickstart.md
  docs/docs/resources.mdx
  docs/docs/tutorials/cms/00 - Introducing the VTEX CMS.md
  docs/docs/tutorials/cms/01 - Configuring your VTEX account.md
  docs/docs/tutorials/cms/02 - Setting up the VTEX Headless CMS in your FastStore project.md
  docs/docs/tutorials/cms/03 - Adding Content Types and Sections to the VTEX Headless CMS.md
  docs/docs/tutorials/cms/04 - Querying the CMS data.md
  docs/docs/tutorials/cms/05 - Adapting the views components.md
  docs/docs/tutorials/cms/Troubleshooting.md
  docs/package.json
  docs/sidebars.js
  docs/src/components/FeedbackForm/FeedbackForm.module.css
  docs/src/components/FeedbackForm/FeedbackForm.tsx
  docs/src/components/SectionImage/SectionImage.module.css
  docs/src/css/custom.css
  docs/src/pages/sections/StarterComponentPage/StarterComponentPage.js
  docs/src/theme/BlogLayout/index.js
  docs/src/theme/BlogListPage/index.js
  docs/src/theme/BlogPostItem/index.js
  docs/src/theme/BlogPostItem/styles.module.css
  docs/src/theme/BlogPostPage/index.js
  docs/src/theme/BlogSidebar/Desktop/index.js
  docs/src/theme/BlogSidebar/Desktop/styles.module.css
  docs/src/theme/BlogSidebar/index.js
  docs/src/theme/BlogTagsListPage/index.js
  docs/src/theme/BlogTagsPostsPage/index.js
  docs/src/theme/BlogTagsPostsPage/styles.module.css
  docs/src/theme/DocCard/index.js
  docs/src/theme/DocCard/styles.module.css
  docs/src/theme/DocCardList/index.js
  docs/src/theme/DocItemFooter/index.js
  docs/src/theme/DocItemFooter/styles.module.css
  docs/src/theme/Layout/index.js
  docs/src/theme/Layout/styles.css
  docs/src/theme/TOC/index.js
  docs/src/theme/TOC/styles.module.css
  docs/static/vercel.json
Labels: documentation

#1310 docs: Add Installing Releases on VTEX Headless CMS
  docs/docs/how-to-guides/cms/vtex-headless-cms/Installing Releases on VTEX Headless CMS.md
Labels: documentation

#1309 Docs/blog/incremental static build
  docs/blog/2022-05-19-webops.md
  docs/static/data/releases.json
Labels: documentation

#1311 Docs/add installing releases cms
  docs/blog/2022-05-19-cms.md
  docs/static/data/releases.json
Labels: documentation

#1313 docs: update cms guides
  docs/docs/how-to-guides/cms/vtex-headless-cms/Enabling private CMS previews.md
  docs/docs/how-to-guides/cms/vtex-headless-cms/Installing Releases on VTEX Headless CMS.md
  docs/docs/how-to-guides/cms/vtex-headless-cms/Sending CMS updates to VTEX IO WebOps.md
  docs/docs/tutorials/cms/01 - Configuring your VTEX account.md
Labels: documentation

#1316 feat: useStorage update onFocus
  packages/sdk/src/storage/useStorage.ts
Labels: enhancement, store-sdk

#1321 fix: Top searches
  packages/api/mocks/AllProductsQuery.ts
  packages/api/mocks/ProductQuery.ts
  packages/api/mocks/SearchQuery.ts
  packages/api/mocks/ValidateCartMutation.ts
  packages/api/src/platforms/vtex/clients/search/index.ts
  packages/api/src/platforms/vtex/index.ts
  packages/api/src/platforms/vtex/resolvers/query.ts
  packages/api/src/platforms/vtex/utils/channel.ts
  packages/api/src/platforms/vtex/utils/contex.ts
  packages/api/src/platforms/vtex/utils/facets.ts
  packages/api/test/mutations.test.ts
  packages/api/test/queries.test.ts
  packages/api/test/schema.test.ts
Labels: bug, store-api

#1322 feat: Search suggestions term count
  packages/api/local/server.ts
  packages/api/src/platforms/vtex/resolvers/searchResult.ts
  packages/api/src/typeDefs/query.graphql
  yarn.lock
Labels: enhancement

#1328 Update openReplay.js
  apps/docs/static/scripts/openReplay.js
Labels: documentation

#1329 docs: Update Hosting a FastStore + VTEX website doc
  apps/docs/blog/2022-05-30-faststore.md
  apps/docs/docs/how-to-guides/platform-integration/vtex/hosting-a-faststore-vtex-website.md
  apps/docs/docs/how-to-guides/platform-integration/vtex/troubleshooting.md
  apps/docs/docs/tutorials/cms/Troubleshooting.md
  apps/docs/docs/tutorials/gatsby/Troubleshooting.mdx
  apps/docs/static/data/doc-update.json
  apps/docs/static/data/releases.json
Labels: documentation

#1319 feat: Trade Policies
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/clients/commerce/types/Session.ts
  packages/api/src/platforms/vtex/resolvers/mutation.ts
  packages/api/src/platforms/vtex/resolvers/query.ts
  packages/api/src/platforms/vtex/resolvers/updateSession.ts
  packages/api/src/platforms/vtex/resolvers/validateSession.ts
  packages/api/src/typeDefs/index.ts
  packages/api/src/typeDefs/mutation.graphql
  packages/api/src/typeDefs/person.graphql
  packages/api/src/typeDefs/query.graphql
  packages/api/src/typeDefs/session.graphql
  packages/api/test/schema.test.ts
  packages/sdk/src/cart/Optimistic.tsx
  packages/sdk/src/index.ts
  packages/sdk/src/session/Provider.tsx
  packages/sdk/src/session/Revalidate.tsx
  packages/sdk/src/session/Session.tsx
  packages/sdk/src/session/useSession.ts
  packages/sdk/src/utils/useValidation.ts
Labels: enhancement, store-sdk, store-api
