Repository vtex/faststore, pull requests merged in 2022-09, with the labels that each got.

#1443 feat: Add `Gift` component
  packages/styles/src/molecules/gift.css
  packages/styles/src/molecules/index.css
  packages/ui/src/index.ts
  packages/ui/src/molecules/Gift/Gift.test.tsx
  packages/ui/src/molecules/Gift/Gift.tsx
  packages/ui/src/molecules/Gift/GiftContent.tsx
  packages/ui/src/molecules/Gift/GiftImage.tsx
  packages/ui/src/molecules/Gift/index.tsx
  packages/ui/src/molecules/Gift/stories/Gift.mdx
  packages/ui/src/molecules/Gift/stories/Gift.stories.tsx
Labels: store-ui, ui-molecule

#1451 Docs/api guides release note
  apps/docs/blog/2022-09-01-faststore.md
  apps/docs/static/data/releases.json
Labels: documentation

#1452 docs: Add glossary
  apps/docs/docs/glossary.mdx
  apps/docs/docs/how-to-guides/performance.md
  apps/docs/docs/how-to-guides/performance/performance.md
  apps/docs/docs/how-to-guides/performance/testing-the-server-side-rendering.md
  apps/docs/sidebars.js
  apps/docs/static/data/doc-update.json
Labels: documentation

#1449 docs: review analytics on faststore
  apps/docs/blog/2022-08-31-faststore.md
  apps/docs/blog/authors.yml
  apps/docs/docs/beta/about.mdx
  apps/docs/docs/conceptual-guides/analytics-on-faststore.md
  apps/docs/docs/conceptual-guides/analytics-on-official-starters.md
  apps/docs/docs/conceptual-guides/analytics-store-framework.md
  apps/docs/docs/reference/sdk/Analytics.md
  apps/docs/docs/reference/sdk/analytics/how-to-extend-types.md
  apps/docs/docs/reference/sdk/analytics/how-to-send-custom-events.md
  apps/docs/docs/reference/sdk/analytics/sendAnalyticsEvent.md
  apps/docs/docs/reference/sdk/analytics/useAnalyticsEvent.md
  apps/docs/sidebars.js
  apps/docs/static/data/doc-update.json
Labels: documentation

#1453 docs: add analyzing a projects bundle size
  apps/docs/docs/how-to-guides/performance/analyzing-a-projects-bundle-size.md
  apps/docs/static/data/doc-update.json
Labels: documentation

#1458 docs: getting started with lighthouse
  apps/docs/docs/how-to-guides/performance/lighthouse.md
  apps/docs/static/data/doc-update.json
  apps/docs/static/data/releases.json
Labels: documentation

#1459 Update lighthouse.md
  apps/docs/docs/how-to-guides/performance/lighthouse.md
Labels: documentation

#1463 Update ProductCard.mdx
  apps/docs/docs/reference/ui/molecules/ProductCard.mdx
Labels: documentation

#1456 feat: Adds OrderSummary component to FastStore UI
  packages/styles/src/molecules/index.css
  packages/styles/src/molecules/order-summary.css
  packages/ui/src/index.ts
  packages/ui/src/molecules/OrderSummary/OrderSummary.test.tsx
  packages/ui/src/molecules/OrderSummary/OrderSummary.tsx
  packages/ui/src/molecules/OrderSummary/index.tsx
  packages/ui/src/molecules/OrderSummary/stories/OrderSummary.mdx
  packages/ui/src/molecules/OrderSummary/stories/OrderSummary.stories.tsx
Labels: enhancement

#1462 refactor: Extract `SkuSelector` component from the starter
  packages/styles/src/molecules/index.css
  packages/styles/src/molecules/sku-selector.css
  packages/ui/src/index.ts
  packages/ui/src/molecules/SkuSelector/SkuSelector.test.tsx
  packages/ui/src/molecules/SkuSelector/SkuSelector.tsx
  packages/ui/src/molecules/SkuSelector/index.tsx
  packages/ui/src/molecules/SkuSelector/stories/SkuSelector.mdx
  packages/ui/src/molecules/SkuSelector/stories/SkuSelector.stories.tsx
Labels: enhancement

#1461 refactor: Extract `CartItem` component from the starter
  packages/styles/src/molecules/cart-item.css
  packages/styles/src/molecules/index.css
  packages/ui/src/index.ts
  packages/ui/src/molecules/CartItem/CartItem.test.tsx
  packages/ui/src/molecules/CartItem/CartItem.tsx
  packages/ui/src/molecules/CartItem/CartItemActions.tsx
  packages/ui/src/molecules/CartItem/CartItemContent.tsx
  packages/ui/src/molecules/CartItem/CartItemImage.tsx
  packages/ui/src/molecules/CartItem/CartItemPrices.tsx
  packages/ui/src/molecules/CartItem/CartItemSummary.tsx
  packages/ui/src/molecules/CartItem/CartItemTitle.tsx
  packages/ui/src/molecules/CartItem/index.tsx
  packages/ui/src/molecules/CartItem/stories/CartItem.mdx
  packages/ui/src/molecules/CartItem/stories/CartItem.stories.tsx
  packages/ui/src/molecules/QuantitySelector/stories/QuantitySelector.mdx
Labels: enhancement

#1466 docs: RN August 2022
  apps/docs/blog/2022-09-13-faststore.md
  apps/docs/static/data/releases.json
  lerna.json
Labels: documentation

#1467 docs: handling-the-impact-of-third-party-scripts
  apps/docs/docs/how-to-guides/performance/handling-the-impact-of-third-party-scripts.md
  apps/docs/static/data/doc-update.json
Labels: documentation

#1468 docs: fix extending graphql example
  apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md
Labels: documentation

#1470 feat(ui): improve extensibility of table and accordion molecules
  packages/ui/src/molecules/Accordion/AccordionItem.tsx
  packages/ui/src/molecules/Accordion/stories/Accordion.mdx
  packages/ui/src/molecules/Table/Table.tsx
Labels: enhancement

#1472 fix(ui): fixes tsconfig.json to exclude storybook types inside .d.ts file
  packages/ui/tsconfig.json
Labels: bug
