Repository vtex/faststore, pull requests merged in 2022-08, with the labels that each got.

#1424 Chore: Updates documentation link
  packages/ui/README.md
Labels: documentation

#1427 feat: Add fowardRef to `ProductTitle`
  packages/ui/src/molecules/ProductTitle/ProductTitle.tsx
Labels: enhancement

#1392 feat: useEffect is not for effects
  .gitignore
  packages/sdk/src/cart/Cart.tsx
  packages/sdk/src/cart/Optimistic.tsx
  packages/sdk/src/cart/Provider.tsx
  packages/sdk/src/cart/index.ts
  packages/sdk/src/cart/useCart.ts
  packages/sdk/src/index.ts
  packages/sdk/src/session/Provider.tsx
  packages/sdk/src/session/Revalidate.tsx
  packages/sdk/src/session/Session.tsx
  packages/sdk/src/session/index.ts
  packages/sdk/src/session/useSession.ts
  packages/sdk/src/storage/useStorage.ts
  packages/sdk/src/store/base.ts
  packages/sdk/src/store/composed.ts
  packages/sdk/src/store/optimistic.ts
  packages/sdk/src/store/persisted.ts
  packages/sdk/src/store/singleton.ts
  packages/sdk/src/utils/compose.ts
  packages/sdk/test/cart/Provider.test.tsx
  packages/sdk/test/cart/index.test.tsx
  packages/sdk/test/session/Provider.test.tsx
  packages/sdk/test/session/index.test.tsx
  packages/sdk/test/storage/useStorage.test.ts
  packages/sdk/test/store/base.test.ts
  packages/sdk/test/store/optimistic.test.ts
  packages/sdk/test/store/persisted.test.ts
  packages/sdk/test/store/singleton.test.ts
  packages/sdk/test/waitFor.ts
  packages/sdk/tsconfig.json
  packages/sdk/types/index.d.ts
Labels: enhancement, performance

#1407 feat: Add skuSelector-related properties to ProductGroup type
  packages/api/mocks/skuVariants.ts
  packages/api/src/platforms/vtex/index.ts
  packages/api/src/platforms/vtex/resolvers/productGroup.ts
  packages/api/src/platforms/vtex/resolvers/skuVariations.ts
  packages/api/src/platforms/vtex/utils/skuVariants.ts
  packages/api/src/typeDefs/index.ts
  packages/api/src/typeDefs/productGroup.graphql
  packages/api/src/typeDefs/skuVariants.graphql
  packages/api/test/vtex.skuVariants.test.ts
Labels: enhancement

#1433 docs: Add FastStore Release Notes
  apps/docs/blog/2022-08-05-faststore.md
  apps/docs/static/data/releases.json
  lerna.json
Labels: documentation

#1434 fix: Join cart items
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
Labels: bug, store-api

#1436 Docs/improvement/extending schema 04082022
  apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md
Labels: documentation

#1445 docs: Fix NextJS and Gatsby sections on using a GraphQL IDE
  apps/docs/blog/2022-08-05-faststore.md
  apps/docs/docs/how-to-guides/faststore-api/explore-the-faststore-api.mdx
  apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md
  apps/docs/docs/how-to-guides/faststore-api/fetching-api-data.mdx
  apps/docs/docs/how-to-guides/faststore-api/using-graphiql-to-explore-the-faststore-api.mdx
Labels: documentation

#1444 feat: Cart with session info
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
  packages/api/src/typeDefs/mutation.graphql
Labels: store-api

#1446 docs: major-changes
  apps/docs/docs/beta/about.mdx
  apps/docs/docs/beta/changes-from-store-framework.mdx
  apps/docs/docs/beta/customer-invitation.mdx
  apps/docs/docs/beta/features-and-capabilities.mdx
  apps/docs/docs/beta/feedback-and-issue-tracking.mdx
  apps/docs/docs/beta/overview.mdx
  apps/docs/docs/docs.mdx
  apps/docs/docs/how-to-guides/platform-integration/vtex/integrating-vtex-checkout.md
  apps/docs/docs/index.mdx
  apps/docs/docs/openapi/headlesscms.yaml
  apps/docs/docs/reference.md
  apps/docs/docs/resources.mdx
  apps/docs/docs/tutorials.mdx
  apps/docs/docusaurus.config.js
  apps/docs/sidebars.js
  apps/docs/src/components/BackgroundCard/BackgroundCard.js
  apps/docs/src/components/BackgroundCard/BackgroundCard.module.css
  apps/docs/src/components/CardGrid/CardGrid.jsx
  apps/docs/src/components/CardGrid/CardGrid.module.css
  apps/docs/src/components/DocFooter/DocFooter.js
  apps/docs/src/components/DocUpdate/DocUpdate.js
  apps/docs/src/components/DocsSection/DocsSection.js
  apps/docs/src/components/FaqQuestion/FaqQuestion.module.css
  apps/docs/src/components/FastStore/FastStore.js
  apps/docs/src/components/FastStore/FastStore.module.css
  apps/docs/src/components/FastStorePackages/FastStorePackages.module.css
  apps/docs/src/components/FastStorePackages/FastStorePackages.tsx
  apps/docs/src/components/Hero/Hero.js
  apps/docs/src/components/Hero/PlaygroundPreview.js
  apps/docs/src/components/InfoCard/InfoCard.module.css
  apps/docs/src/components/LatestUpdates/LatestUpdates.js
  apps/docs/src/components/LatestUpdates/LatestUpdates.module.css
  apps/docs/src/components/PlaygroundShow/index.jsx
  apps/docs/src/components/PlaygroundShow/styles.module.css
  apps/docs/src/components/SectionImage/SectionImage.js
  apps/docs/src/components/SectionImage/SectionImage.module.css
  apps/docs/src/components/StarterComponent/StarterComponent.js
  apps/docs/src/components/ViewAll/ViewAll.js
  apps/docs/src/components/ViewAll/ViewAll.module.css
  apps/docs/src/css/custom.css
  apps/docs/src/pages/index.js
  apps/docs/src/pages/sections/EducationSection/EducationSection.js
  apps/docs/src/pages/sections/FaqPage/FaqPage.js
  apps/docs/src/pages/sections/StarterComponentPage/StarterComponentPage.js
  apps/docs/src/pages/sections/StarterPage/StarterPage.js
  apps/docs/src/pages/sections/UpdatesSection/UpdatesSection.js
  apps/docs/src/theme/BlogSidebar/Desktop/styles.module.css
  apps/docs/src/theme/NotFound.js
  apps/docs/static/img/headless-cms.png
  apps/docs/tailwind.config.js
Labels: documentation

#1448 docs: feat-suggest-edits
  apps/docs/docs/beta/about.mdx
  apps/docs/sidebars.js
  apps/docs/src/components/FeedbackScan/FeedbackScan.js
  apps/docs/src/components/FeedbackScanModal/FeedbackModal.module.css
  apps/docs/src/components/FeedbackScanModal/FeedbackScanModal.js
  apps/docs/src/components/Hero/Hero.js
  apps/docs/src/css/custom.css
  apps/docs/src/theme/DocItem/index.js
Labels: documentation
