Repository vtex/faststore, pull requests merged in 2022-02, with the labels that each got.

#1132 docs: Login integration
  docs/docs/how-to-guides/platform-integration/vtex/integrating-the-vtex-login.md
  docs/sidebars.js
  docs/static/data/doc-update.json
  docs/static/img/how-to-guides/home-template.png
  yarn.lock
Labels: documentation

#1133 Update Starter Lib
  docs/src/components/StarterComponent/StarterComponent.module.css
  docs/src/pages/sections/StarterComponentPage/StarterComponentPage.js
  docs/src/pages/sections/StarterComponentPage/StarterComponentPage.module.css
  docs/src/pages/sections/StarterPage/StarterPage.js
  docs/src/pages/sections/StarterPage/StarterPage.module.css
  docs/src/pages/starters/base.js
  docs/src/pages/starters/storeframework.js
  docs/static/data/starters.json
  docs/static/img/base-starter.png
  docs/static/img/starters/base-starter.png
  docs/static/img/starters/base-store-thumbnail.png
  docs/static/img/starters/cms-base-starter.png
Labels: documentation

#1136 Doc/release notes january
  docs/blog/2022-01-04-faststore.md
  docs/static/data/releases.json
Labels: documentation

#1130 docs: OrderPlaced integration
  docs/docs/how-to-guides/platform-integration/vtex-integration.md
  docs/docs/how-to-guides/platform-integration/vtex/hosting-a-faststore-vtex-website.md
  docs/docs/how-to-guides/platform-integration/vtex/integrating-vtex-checkout.md
  docs/docs/how-to-guides/platform-integration/vtex/integrating-vtex-orderplaced-myaccount.md
  docs/sidebars.js
  docs/src/css/custom.css
  docs/static/data/doc-update.json
  docs/static/img/how-to-guides/checkout-admin.png
  docs/static/img/how-to-guides/gear-button.png
  docs/static/img/how-to-guides/op-order-options.png
  docs/static/img/how-to-guides/order-placed-page.png
  docs/static/img/how-to-guides/orderplacedversion.png
  yarn.lock
Labels: documentation

#1148 fix(api): PDP and PLP breadcrumb list item's URL paths
  packages/api/src/platforms/vtex/resolvers/collection.ts
  packages/api/src/platforms/vtex/resolvers/product.ts
Labels: bug

#1143 fix(ui): Use valid HTML for the Breadcrumb's divider
  docs/docs/reference/ui/molecules/Breadcrumb.mdx
  packages/ui/src/molecules/Breadcrumb/Breadcrumb.test.tsx
  packages/ui/src/molecules/Breadcrumb/Breadcrumb.tsx
  packages/ui/src/molecules/Breadcrumb/stories/Breadcrumb.mdx
  themes/theme-b2c-tailwind/src/molecules/breadcrumb.css
Labels: bug

#1160 fix: Cart item availability
  packages/api/src/platforms/vtex/clients/fetch.ts
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
Labels: bug, store-api
