Repository vtex/faststore, pull requests merged in 2022-10, with the labels that each got.

#1479 docs: RN CMS preview
  apps/docs/blog/2022-10-05-cms.md
  apps/docs/static/data/releases.json
Labels: documentation

#1477 Fix meta and breadcrumbList for collections
  packages/api/src/platforms/vtex/resolvers/collection.ts
Labels: bug, store-api

#1483 feat: Add watch capability to dev command
  packages/cli/package.json
  packages/cli/src/commands/dev.ts
  packages/cli/src/utils/root.ts
  yarn.lock
Labels: enhancement
