Repository vtex/faststore, pull requests merged in 2022-06, with the labels that each got.

#1337 Update hosting-a-faststore-vtex-website.md
  apps/docs/docs/how-to-guides/platform-integration/vtex/hosting-a-faststore-vtex-website.md
Labels: documentation

#1340 Docs: May Release Notes
  apps/docs/blog/2022-05-06-basestore.md
  apps/docs/blog/2022-05-06-faststore.md
  apps/docs/blog/2022-06-03-basestore.md
  apps/docs/blog/2022-06-03-faststore.md
  apps/docs/static/data/releases.json
Labels: documentation

#1350 fix: Spot pricing sort for lowPrice/highPrice
  packages/api/src/platforms/vtex/resolvers/aggregateOffer.ts
  packages/api/src/platforms/vtex/utils/productStock.ts
Labels: bug, store-api

#1360 fix: api test inconsistencies
  packages/api/test/mutations.test.ts
  packages/api/test/queries.test.ts
Labels: bug, store-api

#1361 feat: Export API Errors
  packages/api/src/index.ts
  packages/api/src/platforms/errors.ts
  packages/api/src/platforms/vtex/loaders/collection.ts
  packages/api/src/platforms/vtex/loaders/sku.ts
  packages/api/src/platforms/vtex/utils/errors.ts
Labels: enhancement, store-api

#1344 Docs/api md docs 2
  apps/docs/docs/how-to-guides/faststore-api/creating-resolvers.md
  apps/docs/docs/how-to-guides/faststore-api/extending-the-faststore-api.md
  apps/docs/docs/reference/api/enums.md
  apps/docs/docs/reference/api/faststore-api.md
  apps/docs/docs/reference/api/get-started.md
  apps/docs/docs/reference/api/inputs.md
  apps/docs/docs/reference/api/mutations.md
  apps/docs/docs/reference/api/mutations/cart.mdx
  apps/docs/docs/reference/api/mutations/session.mdx
  apps/docs/docs/reference/api/objects.md
  apps/docs/docs/reference/api/queries.md
  apps/docs/docs/reference/api/queries/allCollections.mdx
  apps/docs/docs/reference/api/queries/allProducts.mdx
  apps/docs/docs/reference/api/queries/collection.mdx
  apps/docs/docs/reference/api/queries/product.mdx
  apps/docs/docs/reference/api/queries/search.mdx
  apps/docs/docs/reference/api/scalars.mdx
  apps/docs/package.json
  apps/docs/sidebars.js
  apps/docs/src/components/GraphQLExplorer/GraphQLExplorer.tsx
  apps/docs/src/components/PropsComponent/PropsComponent.tsx
  apps/docs/src/css/custom.css
  apps/docs/static/data/doc-update.json
  packages/api/src/typeDefs/cart.graphql
  packages/api/src/typeDefs/collection.graphql
  packages/api/src/typeDefs/mutation.graphql
  packages/api/src/typeDefs/order.graphql
  packages/api/src/typeDefs/pageInfo.graphql
  packages/api/src/typeDefs/query.graphql
  packages/api/src/typeDefs/session.graphql
  packages/api/src/typeDefs/status.graphql
Labels: documentation

#1365 docs: troubleshooting docs
  apps/docs/docs/how-to-guides/troubleshooting.md
  apps/docs/docs/how-to-guides/troubleshooting/identifying-development-errors-and-starter-bugs.md
  apps/docs/docs/how-to-guides/troubleshooting/tracing-the-error-source.md
  apps/docs/sidebars.js
  apps/docs/src/css/custom.css
  apps/docs/static/data/doc-update.json
Labels: documentation

#1355 Doc out of stock
  apps/docs/docs/reference/ui/molecules/Card.mdx
  apps/docs/docs/reference/ui/organisms/OutOfStock.mdx
  apps/docs/docusaurus.config.js
  apps/docs/package.json
  apps/docs/sidebars.js
  apps/docs/src/theme/Playground/styles.module.css
  apps/docs/src/theme/ReactLiveScope/index.tsx
  apps/docs/static/data/doc-update.json
Labels: documentation

#1339 Docs: `ProductCard` documentation
  apps/docs/blog/2022-02-04-faststore.md
  apps/docs/docs/reference/ui/molecules/Card.mdx
  apps/docs/docs/reference/ui/molecules/ProductCard.mdx
  apps/docs/docs/reference/ui/organisms/OutOfStock.md
  apps/docs/static/data/doc-update.json
Labels: documentation

#1370 docs: Update doc footer and improve vtex integration guide
  apps/docs/docs/how-to-guides/platform-integration/vtex-integration.md
  apps/docs/docs/reference.md
  apps/docs/docs/tutorials/cms/00 - Introducing the VTEX CMS.md
  apps/docs/docs/tutorials/cms/01 - Configuring your VTEX account.md
  apps/docs/docs/tutorials/cms/02 - Setting up the VTEX Headless CMS in your FastStore project.md
  apps/docs/docs/tutorials/cms/03 - Adding Content Types and Sections to the VTEX Headless CMS.md
  apps/docs/docs/tutorials/cms/04 - Querying the CMS data.md
  apps/docs/docs/tutorials/cms/05 - Adapting the views components.md
  apps/docs/docs/tutorials/cms/Troubleshooting.md
  apps/docs/docs/tutorials/gatsby/01 - Introducting Gatsby.mdx
  apps/docs/docs/tutorials/gatsby/02 - Setting up your development environment.mdx
  apps/docs/docs/tutorials/gatsby/03 - Creating your first SFJ store.mdx
  apps/docs/docs/tutorials/gatsby/04 - Understanding the project structure.md
  apps/docs/docs/tutorials/gatsby/05 - Using components.md
  apps/docs/docs/tutorials/gatsby/06 - Styling components.mdx
  apps/docs/docs/tutorials/gatsby/Troubleshooting.mdx
  apps/docs/docusaurus.config.js
  apps/docs/sidebars.js
  apps/docs/src/components/DocFooter/DocFooter.js
  apps/docs/src/css/custom.css
  apps/docs/src/pages/sections/EducationSection/EducationSection.js
  apps/docs/src/theme/DocItem/index.js
  apps/docs/src/theme/DocItem/styles.module.css
  apps/docs/src/theme/DocItemFooter/index.js
  apps/docs/src/theme/DocItemFooter/styles.module.css
  apps/docs/src/theme/EditThisPage/index.js
  apps/docs/src/theme/PaginatorNavLink/index.js
Labels: documentation

#1364 feat: Price range filter on PLP
  apps/docs/docs/reference/ui/molecules/PriceRange.mdx
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/search/index.ts
  packages/api/src/platforms/vtex/clients/search/types/FacetSearchResult.ts
  packages/api/src/platforms/vtex/index.ts
  packages/api/src/platforms/vtex/resolvers/faceValue.ts
  packages/api/src/platforms/vtex/resolvers/facet.ts
  packages/api/src/platforms/vtex/resolvers/facetValue.ts
  packages/api/src/platforms/vtex/resolvers/offer.ts
  packages/api/src/platforms/vtex/resolvers/searchResult.ts
  packages/api/src/platforms/vtex/utils/facets.ts
  packages/api/src/typeDefs/facet.graphql
  packages/api/test/__snapshots__/queries.test.ts.snap
  packages/api/test/schema.test.ts
  packages/sdk/src/index.ts
  packages/sdk/src/search/facets.ts
  packages/sdk/src/search/serializer.ts
  packages/sdk/src/search/useInfiniteSearchState.ts
  packages/sdk/src/search/useSearchState.ts
  packages/sdk/test/search/Provider.test.tsx
  packages/ui/src/atoms/Slider/Slider.test.tsx
  packages/ui/src/atoms/Slider/Slider.tsx
  packages/ui/src/molecules/PriceRange/PriceRange.test.tsx
  packages/ui/src/molecules/PriceRange/PriceRange.tsx
Labels: enhancement, store-ui, store-sdk, store-api

#1376 docs: add Hero doc
  apps/docs/docs/reference/ui/atoms/Badge.mdx
  apps/docs/docs/reference/ui/molecules/Card.mdx
  apps/docs/docs/reference/ui/organisms/Hero.mdx
  apps/docs/docs/reference/ui/organisms/OutOfStock.mdx
  apps/docs/static/data/doc-update.json
Labels: documentation

#1381 Update openReplay.js
  apps/docs/static/scripts/openReplay.js
Labels: documentation

#1382 docs: Add ComponentCard
  apps/docs/docs/reference/ui/atoms/Badge.mdx
  apps/docs/docs/reference/ui/atoms/Button.mdx
  apps/docs/docs/reference/ui/atoms/Checkbox.mdx
  apps/docs/docs/reference/ui/atoms/Icon.mdx
  apps/docs/docs/reference/ui/atoms/Incentive.mdx
  apps/docs/docs/reference/ui/atoms/Input.mdx
  apps/docs/docs/reference/ui/atoms/Label.mdx
  apps/docs/docs/reference/ui/atoms/Link.mdx
  apps/docs/docs/reference/ui/atoms/List.mdx
  apps/docs/docs/reference/ui/atoms/Overlay.mdx
  apps/docs/docs/reference/ui/atoms/Popover.mdx
  apps/docs/docs/reference/ui/atoms/Price.mdx
  apps/docs/docs/reference/ui/atoms/Radio.mdx
  apps/docs/docs/reference/ui/atoms/Select.mdx
  apps/docs/docs/reference/ui/atoms/Skeleton.mdx
  apps/docs/docs/reference/ui/atoms/Slider.mdx
  apps/docs/docs/reference/ui/atoms/Spinner.mdx
  apps/docs/docs/reference/ui/atoms/TextArea.mdx
  apps/docs/docs/reference/ui/components.md
  apps/docs/docs/reference/ui/molecules/Accordion.mdx
  apps/docs/docs/reference/ui/molecules/Alert.mdx
  apps/docs/docs/reference/ui/molecules/Banner.mdx
  apps/docs/docs/reference/ui/molecules/Breadcrumb.mdx
  apps/docs/docs/reference/ui/molecules/Bullets.mdx
  apps/docs/docs/reference/ui/molecules/Card.mdx
  apps/docs/docs/reference/ui/molecules/Carousel.mdx
  apps/docs/docs/reference/ui/molecules/Dropdown.mdx
  apps/docs/docs/reference/ui/molecules/Form.mdx
  apps/docs/docs/reference/ui/molecules/IconButton.mdx
  apps/docs/docs/reference/ui/molecules/LoadingButton.mdx
  apps/docs/docs/reference/ui/molecules/Modal.mdx
  apps/docs/docs/reference/ui/molecules/PaymentMethods.mdx
  apps/docs/docs/reference/ui/molecules/PriceRange.mdx
  apps/docs/docs/reference/ui/molecules/ProductCard.mdx
  apps/docs/docs/reference/ui/molecules/QuantitySelector.mdx
  apps/docs/docs/reference/ui/molecules/RadioGroup.mdx
  apps/docs/docs/reference/ui/molecules/SearchInput.mdx
  apps/docs/docs/reference/ui/molecules/Table.mdx
  apps/docs/docs/reference/ui/organisms/Hero.mdx
  apps/docs/docs/reference/ui/organisms/OutOfStock.mdx
  apps/docs/sidebars.js
  apps/docs/src/components/ComponentCard/ComponentCard.js
  apps/docs/src/components/ComponentsOverview/ComponentsOverview.js
  apps/docs/src/css/custom.css
  apps/docs/static/data/doc-update.json
Labels: documentation

#1378 Mutation markdown docs
  apps/docs/docs/reference/api/mutations/cart.mdx
  apps/docs/docs/reference/api/mutations/session.mdx
  apps/docs/static/data/doc-update.json
  packages/api/src/typeDefs/facet.graphql
Labels: documentation
