Repository vtex/faststore, pull requests merged in 2023-05, with the labels that each got.

#1739 Docs: Updates Icons docs + general updates
  apps/site/pages/components/atoms/icon.mdx
  apps/site/pages/docs/component-customization/override-component.mdx
  apps/site/pages/docs/customizing.mdx
  apps/site/pages/docs/getting-started/onboarding.mdx
  apps/site/pages/docs/global-tokens/typography.mdx
  apps/site/pages/docs/icons.mdx
  apps/site/pages/docs/themes/midnight.mdx
  apps/site/pages/docs/themes/soft-blue.mdx
  apps/site/pages/docs/troubleshooting/identifying-development-errors-and-starter-bugs.mdx
  apps/site/pages/index.mdx
  packages/components/src/atoms/Icon/Icon.tsx
  packages/core/src/components/common/Footer/Footer.tsx
Labels: documentation

#1731 Doc: setting up
  apps/site/pages/docs/getting-started/faststore-cli.mdx
  apps/site/pages/docs/getting-started/getting-started-overview.mdx
  apps/site/pages/docs/getting-started/next-steps.mdx
  apps/site/pages/docs/getting-started/project-structure.mdx
  apps/site/pages/docs/getting-started/settingup-project.mdx
Labels: documentation

#1738 Doc: How to Create a Component
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/component-customization/creating-component.mdx
Labels: documentation

#1742 Update onboarding.mdx
  apps/site/pages/docs/getting-started/onboarding.mdx
Labels: documentation

#1735 Feat: Adds `Carousel` Component 782
  apps/site/components/Carousel/CarouselUsage.tsx
  apps/site/components/OverviewSection/OverviewSection.tsx
  apps/site/components/ProductShelf/ProductShelfCarouselUsage.tsx
  apps/site/components/ProductShelf/ProductShelfUsage.tsx
  apps/site/mocks/products.ts
  apps/site/pages/components/molecules/carousel.mdx
  apps/site/pages/components/organisms/product-grid.mdx
  apps/site/pages/components/organisms/product-shelf.mdx
  apps/site/styles/custom-nextra.css
  packages/components/src/hooks/index.ts
  packages/components/src/hooks/useSlideVisibility.ts
  packages/components/src/hooks/useSlider.ts
  packages/components/src/index.ts
  packages/components/src/molecules/Carousel/Carousel.tsx
  packages/components/src/molecules/Carousel/CarouselBullets.tsx
  packages/components/src/molecules/Carousel/CarouselItem.tsx
  packages/components/src/molecules/Carousel/index.ts
  packages/core/src/components/cms/RenderSections.tsx
  packages/core/src/components/sections/ProductShelf/ProductShelf.tsx
  packages/core/src/components/sections/ProductShelf/section.module.scss
  packages/core/src/components/skeletons/ProductShelfSkeleton/ProductShelfSkeleton.tsx
  packages/core/src/components/ui/Carousel/Carousel.tsx
  packages/ui/src/components/molecules/Bullets/index.ts
  packages/ui/src/components/molecules/Carousel/Arrows.tsx
  packages/ui/src/components/molecules/Carousel/index.ts
  packages/ui/src/components/molecules/Carousel/styles.scss
  packages/ui/src/components/molecules/NavbarLinks/styles.scss
  packages/ui/src/components/organisms/ProductShelf/styles.scss
  packages/ui/src/hooks/useSlider/index.ts
  packages/ui/src/index.ts
Labels: ui-molecule, evergreen

#1745 Feat: Add PLP Content-type e refacts sections to use CamelCase
  packages/core/cms/faststore/content-types.json
  packages/core/cms/faststore/sections.json
Labels: CMS

#1741 Fix: `Button` sizing respecting Lighthouse limit
  apps/site/components/SectionItem/section-item.module.css
  apps/site/pages/components/atoms/button.mdx
  apps/site/pages/components/molecules/icon-button.mdx
  apps/site/pages/components/molecules/navbar-links.mdx
  apps/site/pages/components/molecules/region-bar.mdx
  apps/site/pages/components/molecules/search-input-field.mdx
  apps/site/pages/components/organisms/image-gallery.mdx
  packages/components/src/atoms/Button/Button.tsx
  packages/components/src/molecules/Alert/Alert.tsx
  packages/components/src/molecules/IconButton/IconButton.tsx
  packages/components/src/molecules/InputField/InputField.tsx
  packages/components/src/molecules/LinkButton/LinkButton.tsx
  packages/components/src/molecules/RegionBar/RegionBar.tsx
  packages/components/src/molecules/SearchInputField/SearchInputField.tsx
  packages/core/src/components/common/Footer/section.module.scss
  packages/core/src/components/region/RegionButton/RegionButton.tsx
  packages/core/src/components/sections/BannerNewsletter/section.module.scss
  packages/core/src/components/ui/Button/ButtonSignIn/ButtonSignIn.tsx
  packages/ui/src/components/atoms/Button/styles.scss
  packages/ui/src/components/molecules/Accordion/styles.scss
  packages/ui/src/components/molecules/Alert/styles.scss
  packages/ui/src/components/molecules/Banner/styles.scss
  packages/ui/src/components/molecules/BuyButton/styles.scss
  packages/ui/src/components/molecules/InputField/styles.scss
  packages/ui/src/components/molecules/LinkButton/styles.scss
  packages/ui/src/components/molecules/NavbarLinks/styles.scss
  packages/ui/src/components/molecules/RegionBar/styles.scss
  packages/ui/src/components/molecules/SearchInputField/styles.scss
  packages/ui/src/components/organisms/Hero/styles.scss
  packages/ui/src/components/organisms/ImageGallery/styles.scss
Labels: bug

#1748 Update settingup-project.mdx
  apps/site/pages/docs/getting-started/settingup-project.mdx
Labels: documentation

#1751 Fix: Lighthouse Performance 🟢
  packages/components/src/atoms/Button/Button.tsx
  packages/components/src/molecules/Alert/Alert.tsx
  packages/components/src/molecules/Dropdown/DropdownItem.tsx
  packages/components/src/molecules/Gift/Gift.tsx
  packages/components/src/molecules/LinkButton/LinkButton.tsx
  packages/components/src/molecules/SearchAutoComplete/SearchAutoCompleteTerm.tsx
  packages/components/src/molecules/SearchHistory/SearchHistoryTerm.tsx
  packages/components/src/molecules/Tag/Tag.tsx
  packages/components/src/molecules/Toast/Toast.tsx
  packages/components/src/organisms/Hero/HeroHeader.tsx
  packages/core/src/components/navigation/Navbar/Navbar.tsx
  packages/core/src/components/navigation/NavbarLinks/NavbarLinks.tsx
  packages/core/src/components/navigation/NavbarSlider/NavbarSlider.tsx
  packages/core/src/components/navigation/NavbarSlider/section.module.scss
  packages/core/src/components/product/ProductCard/ProductCard.tsx
  packages/core/src/components/sections/Hero/Hero.tsx
  packages/core/src/components/sections/ProductGallery/ProductGallery.tsx
  packages/core/src/components/sections/ProductGallery/ProductGalleryPage.tsx
  packages/core/src/components/ui/Breadcrumb/Breadcrumb.tsx
  packages/core/src/components/ui/Gift/Gift.tsx
  packages/ui/src/components/molecules/Gift/styles.scss
  packages/ui/src/components/organisms/Hero/styles.scss
Labels: performance

#1758 Docs: Updates override components doc page
  apps/site/pages/docs/component-customization/override-component.mdx
Labels: documentation

#1747 Feat: Pages with `RenderSection` + `Breadcrumb` section CMS
  packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx
  packages/components/src/molecules/Breadcrumb/HomeLink.tsx
  packages/core/cms/faststore/content-types.json
  packages/core/src/components/sections/Breadcrumb/Breadcrumb.tsx
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/ui/Breadcrumb/Breadcrumb.tsx
  packages/core/src/pages/[...slug].tsx
  packages/core/src/pages/[slug]/p.tsx
  packages/core/src/pages/index.tsx
  packages/core/src/pages/s.tsx
  packages/core/src/server/cms.ts
Labels: evergreen, CMS

#1771 docs: Adds Hero's props
  apps/site/pages/components/organisms/hero.mdx
Labels: documentation

#1762 Doc: Update introduction
  apps/site/pages/docs/index.mdx
Labels: documentation

#1774 Docs: Checkbox Field component props
  apps/site/components/utilities/propsSection.ts
  apps/site/pages/components/molecules/checkbox-field.mdx
  packages/components/src/molecules/CheckboxField/CheckboxField.tsx
Labels: documentation

#1755 Doc: Onboarding review
  apps/site/pages/docs/getting-started/0-getting-started-overview.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/dashboard.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/onboarding.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/overview.mdx
  apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
  apps/site/pages/docs/getting-started/3-project-structure.mdx
  apps/site/pages/docs/getting-started/4-faststore-cli.mdx
  apps/site/pages/docs/getting-started/5-next-steps.mdx
  apps/site/pages/docs/getting-started/_meta.json
  apps/site/pages/docs/getting-started/getting-started-overview.mdx
  apps/site/pages/docs/getting-started/onboarding.mdx
Labels: documentation

#1769 Doc: Add Reference section
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/component-customization/override-component.mdx
  apps/site/pages/docs/reference-guides/list-of-available-native-sections.mdx
  apps/site/pages/docs/reference-guides/list-of-overridable-components-for-each-native-section.mdx
Labels: documentation

#1740 feat: Adjust `ProductDetails` for CMS
  packages/components/src/molecules/BuyButton/BuyButton.tsx
  packages/core/cms/faststore/sections.json
  packages/core/src/components/sections/ProducDetailsContent/index.ts
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/ui/ProductDescription/ProductDescription.stories.mdx
  packages/core/src/components/ui/ProductDescription/ProductDescription.tsx
  packages/core/src/components/ui/ProductDescription/index.ts
  packages/core/src/components/ui/ProductDetails/AddToCartLoadingSkeleton.tsx
  packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx
  packages/core/src/components/ui/ProductDetails/index.ts
  packages/core/src/components/ui/ShippingSimulation/ShippingSimulation.tsx
  packages/ui/src/components/organisms/ProductDetails/styles.scss
Labels: evergreen

#1754 Windows-fix: use path instead of `/` for handling paths
  packages/cli/src/utils/directory.ts
  packages/cli/src/utils/generate.ts
Labels: evergreen

#1782 add props to component
  apps/site/pages/components/atoms/input.mdx
  apps/site/pages/components/atoms/select.mdx
  apps/site/pages/components/molecules/alert.mdx
  apps/site/pages/components/molecules/breadcrumb.mdx
  apps/site/pages/components/molecules/buy-button.mdx
  apps/site/pages/components/molecules/icon-button.mdx
  packages/components/src/molecules/Breadcrumb/Breadcrumb.tsx
  packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx
  packages/components/src/molecules/Breadcrumb/BreadcrumbPure.tsx
Labels: documentation

#1765 Doc: Go-live track
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/go-live/1-setting-up-vtex-account-for-faststore.mdx
  apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
  apps/site/pages/docs/go-live/3-integrating-the-the-vtex-login.mdx
  apps/site/pages/docs/go-live/4-integrating-the-vtex-checkout.mdx
  apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
  apps/site/pages/docs/go-live/before-you-start.mdx
  apps/site/pages/docs/go-live/overview.mdx
Labels: documentation

#1797 Docs: Setting up VTEX account for FastStore
  apps/site/components/SectionItem/section-item.module.css
  apps/site/pages/components/index.mdx
  apps/site/pages/docs/component-customization/creating-component.mdx
  apps/site/pages/docs/component-customization/override-component.mdx
  apps/site/pages/docs/getting-started/0-getting-started-overview.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/onboarding.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/overview.mdx
  apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
  apps/site/pages/docs/getting-started/3-project-structure.mdx
  apps/site/pages/docs/getting-started/4-faststore-cli.mdx
  apps/site/pages/docs/global-tokens/colors.mdx
  apps/site/pages/docs/index.mdx
  apps/site/pages/docs/setting-up-a-vtex-account.mdx
  apps/site/pages/docs/troubleshooting/analytics-and-partytown.mdx
  apps/site/pages/docs/troubleshooting/tracing-the-error-source.mdx
  apps/site/styles/custom-nextra.css
Labels: documentation

#1799 Feat: Override `WebFonts`
  apps/site/pages/docs/global-tokens/typography.mdx
  packages/core/src/customizations/GlobalOverrides.tsx
  packages/core/src/customizations/components/overrides/WebFonts.tsx
  packages/core/src/customizations/fonts/WebFonts.tsx
  packages/core/src/pages/_document.tsx
Labels: evergreen
