Repository vtex/faststore, pull requests merged in 2023-03, with the labels that each got.

#1658 feat: Add initial support to Intelligent Search redirects
  packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts
Labels: enhancement

#1649 feat: Adds `Slideover` component
  apps/site/components/SlideOver/SlideOverUsage.tsx
  apps/site/pages/components/organisms/hero.mdx
  apps/site/pages/components/organisms/slide-over.mdx
  apps/site/pages/custom-nextra.css
  packages/components/src/index.ts
  packages/components/src/molecules/Modal/ModalHeader.tsx
  packages/components/src/organisms/Hero/HeroHeader.tsx
  packages/components/src/organisms/Hero/index.tsx
  packages/components/src/organisms/SlideOver/SlideOver.tsx
  packages/components/src/organisms/SlideOver/SlideOverHeader.tsx
  packages/components/src/organisms/SlideOver/index.ts
  packages/core/src/components/cart/CartSidebar/CartSidebar.stories.mdx
  packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
  packages/core/src/components/cart/CartSidebar/cart-sidebar.module.scss
  packages/core/src/components/common/Navbar/NavbarSlider.tsx
  packages/core/src/components/common/Navbar/navbar-slider.module.scss
  packages/core/src/components/regionalization/RegionalizationModal/RegionalizationModalContent.tsx
  packages/core/src/components/search/Filter/FilterSlider.stories.mdx
  packages/core/src/components/search/Filter/FilterSlider.tsx
  packages/core/src/components/search/Filter/filter-slider.module.scss
  packages/core/src/components/sections/Hero/Hero.tsx
  packages/core/src/components/ui/SlideOver/SlideOver.stories.mdx
  packages/core/src/components/ui/SlideOver/index.ts
  packages/ui/src/components/organisms/SlideOver/styles.scss
  packages/ui/src/styles/components.scss
Labels: documentation, ui-organism

#1660 Fix/add context variables cart mutation 1.x
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
Labels: bug

#1659 fix(api): add context variables cart mutation
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
Labels: bug

#1673 Feat: Updates `PropsSection`
  apps/site/components/PropsSection/PropsSection.tsx
  apps/site/components/PropsSection/props-section.module.css
  apps/site/components/utilities/propsSection.ts
  apps/site/package.json
  apps/site/pages/components/atoms/badge.mdx
  apps/site/pages/components/atoms/button.mdx
  apps/site/pages/components/atoms/checkbox.mdx
  apps/site/pages/components/molecules/accordion.mdx
  packages/components/src/atoms/Badge/Badge.tsx
  yarn.lock
Labels: documentation

#1672 Feat: Adds `Toast` Component
  apps/site/components/Toast/ToastUsage.tsx
  apps/site/pages/components/molecules/toast.mdx
  apps/site/pages/docs/icons.mdx
  packages/components/src/assets/SealCheck.tsx
  packages/components/src/assets/SealWarning.tsx
  packages/components/src/assets/index.ts
  packages/components/src/hooks/UIProvider.tsx
  packages/components/src/hooks/index.ts
  packages/components/src/index.ts
  packages/components/src/molecules/Toast/Toast.tsx
  packages/components/src/molecules/Toast/index.ts
  packages/core/src/Layout.tsx
  packages/core/src/components/common/Toast/Toast.tsx
  packages/core/src/components/sections/Newsletter/Newsletter.tsx
  packages/core/src/components/ui/Toast/Toast.stories.mdx
  packages/ui/src/components/molecules/Toast/styles.scss
  packages/ui/src/styles/components.scss
Labels: ui-molecule

#1683 Feat: List toast's component props fs-632
  apps/site/pages/components/molecules/toast.mdx
Labels: documentation

#1685 Feat: Add `OutOfStock` components
  apps/site/pages/components/organisms/out-of-stock.mdx
  apps/site/pages/components/organisms/payment-methods.mdx
  apps/site/pages/docs/icons.mdx
  packages/components/src/assets/BellRinging.tsx
  packages/components/src/assets/index.ts
  packages/components/src/atoms/Loader/Loader.tsx
  packages/components/src/index.ts
  packages/components/src/organisms/OutOfStock/OutOfStock.tsx
  packages/components/src/organisms/OutOfStock/index.tsx
  packages/core/src/components/product/OutOfStock/OutOfStock.stories.mdx
  packages/core/src/components/product/OutOfStock/OutOfStock.tsx
  packages/core/src/components/product/OutOfStock/index.ts
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/sections/ProductDetails/product-details.module.scss
  packages/ui/src/components/organisms/OutOfStock/OutOfStock.tsx
  packages/ui/src/components/organisms/OutOfStock/OutOfStockMessage.tsx
  packages/ui/src/components/organisms/OutOfStock/OutOfStockTitle.tsx
  packages/ui/src/components/organisms/OutOfStock/index.tsx
  packages/ui/src/components/organisms/OutOfStock/styles.scss
  packages/ui/src/index.ts
  packages/ui/src/styles/components.scss
Labels: ui-organism

#1690 Fix: `PaymentMethods` Flag size
  apps/site/pages/components/organisms/payment-methods.mdx
  packages/ui/src/components/organisms/PaymentMethods/styles.scss
Labels: bug

#1698 docs: Updates midnight theme stylesheet
  apps/site/pages/docs/themes/midnight.mdx
  apps/site/pages/docs/themes/soft-blue.mdx
  packages/core/src/styles/themes/midnight.scss
Labels: documentation

#1684 Docs: How to override or customize native section components
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/component-customization/override-component.mdx
Labels: documentation

#1689 Feat: Adds `ShippingSimulation` Components.
  apps/site/components/ShippingSimulation/ShippingSimulationUsage.tsx
  apps/site/pages/components/molecules/sku-selector.mdx
  apps/site/pages/components/organisms/shipping-simulation.mdx
  packages/components/src/assets/ArrowSquareOut.tsx
  packages/components/src/assets/index.ts
  packages/components/src/index.ts
  packages/components/src/organisms/ShippingSimulation/ShippingSimulation.tsx
  packages/components/src/organisms/ShippingSimulation/index.tsx
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
  packages/core/src/components/ui/ShippingSimulation/ShippingSimulation.tsx
  packages/core/src/components/ui/ShippingSimulation/useShippingSimulation.ts
  packages/ui/src/components/organisms/ShippingSimulation/styles.scss
  packages/ui/src/index.ts
  packages/ui/src/styles/components.scss
  yarn.lock
Labels: ui-organism
