Repository vtex/faststore, pull requests merged in 2023-06, with the labels that each got.

#1811 Doc: Fix node version recommendation
  apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
Labels: documentation

#1809 integrating checkout
  apps/site/pages/docs/go-live/4-integrating-the-vtex-checkout.mdx
  apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
  apps/site/pages/docs/go-live/before-you-start.mdx
Labels: documentation

#1815 fix: Product description mock data
  packages/components/src/atoms/Link/Link.tsx
  packages/components/src/organisms/OutOfStock/OutOfStock.tsx
  packages/core/src/components/sections/Newsletter/Newsletter.tsx
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/ui/Link/Link.tsx
  packages/core/src/components/ui/ProductDescription/ProductDescription.tsx
Labels: evergreen

#1803 Docs: Configuring external DNS for a custom domain
  apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
Labels: documentation

#1817 fix: A11y tests
  packages/core/cypress/integration/a11y.test.js
  packages/core/src/components/sections/Navbar/Navbar.tsx
Labels: evergreen

#1824 chore: Skip a11y tests
  packages/core/cypress/integration/a11y.test.js
Labels: evergreen

#1791 Update override-component.mdx
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/component-customization/component-customization-overview.mdx
  apps/site/pages/docs/component-customization/creating-a-new-section.mdx
  apps/site/pages/docs/component-customization/creating-component.mdx
  apps/site/pages/docs/component-customization/override-component.mdx
  apps/site/pages/docs/component-customization/overriding-a-native-component.mdx
  apps/site/pages/docs/component-customization/overriding-components-props.mdx
  apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
Labels: documentation

#1827 Docs: removing callouts and other updates
  apps/site/pages/docs/component-customization/creating-a-new-section.mdx
  apps/site/pages/docs/getting-started/0-getting-started-overview.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/onboarding.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/overview.mdx
  apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
  apps/site/pages/docs/getting-started/3-project-structure.mdx
  apps/site/pages/docs/getting-started/4-faststore-cli.mdx
  apps/site/pages/docs/getting-started/5-next-steps.mdx
  apps/site/pages/docs/go-live/1-setting-up-vtex-account-for-faststore.mdx
  apps/site/pages/docs/setting-up-a-vtex-account.mdx
Labels: documentation

#1829 feat: Generates CMS webhook URLs json file from the store's config
  packages/cli/src/utils/directory.ts
  packages/cli/src/utils/generate.ts
  packages/core/cms-webhook-urls.json
Labels: evergreen

#1835 fix: `BannerText` component
  packages/core/src/components/sections/BannerText/BannerText.tsx
Labels: bug

#1832 Chore: Updates site description
  apps/site/public/favicon.svg
  apps/site/styles/custom-nextra.css
  apps/site/theme.config.tsx
  packages/core/cms/faststore/content-types.json
Labels: documentation

#1813 Docs: List of available sections and overridable components
  apps/site/pages/docs/reference-guides/list-of-available-native-sections.mdx
  apps/site/pages/docs/reference-guides/list-of-native-sections.mdx
  apps/site/pages/docs/reference-guides/list-of-overridable-components-for-each-native-section.mdx
  apps/site/styles/custom-nextra.css
Labels: documentation

#1844 Doc: Component Override Section & Improvements
  apps/site/package.json
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/building-sections/component-customization-overview.mdx
  apps/site/pages/docs/building-sections/creating-a-new-section.mdx
  apps/site/pages/docs/building-sections/overriding-a-native-component.mdx
  apps/site/pages/docs/building-sections/overriding-components-props.mdx
  apps/site/pages/docs/getting-started-overview.mdx
  apps/site/pages/docs/getting-started-requirements.mdx
  apps/site/pages/docs/getting-started/0-getting-started-overview.mdx
  apps/site/pages/docs/getting-started/3-project-structure.mdx
  apps/site/pages/docs/getting-started/_meta.json
  apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
  apps/site/pages/docs/go-live/4-integrating-the-vtex-checkout.mdx
  apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
  apps/site/pages/docs/go-live/overview.mdx
  apps/site/pages/docs/troubleshooting/overview.mdx
  apps/site/styles/custom-nextra.css
  yarn.lock
Labels: documentation

#1861 Docs: improve requirements
  apps/site/pages/docs/getting-started-requirements.mdx
Labels: documentation

#1860 Docs: review CLI guide
  apps/site/pages/docs/getting-started/4-faststore-cli.mdx
Labels: documentation
