Repository vtex/faststore, pull requests merged in 2023-09, with the labels that each got.

#1993 Fix: Improves `PriceRange` accessibility
  packages/components/src/atoms/Slider/Slider.tsx
Labels: bug

#1989 Fix: Improves `Breadcrumb` accessibility
  packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx
  packages/components/src/molecules/Dropdown/DropdownButton.tsx
  packages/ui/src/components/molecules/Breadcrumb/styles.scss
Labels: bug

#1983 fix: minicart price round
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
Labels: bug

#2004 Update creating-a-new-section.mdx
  apps/site/pages/docs/building-sections/creating-a-new-section.mdx
Labels: documentation

#1933 docs: Updates Cypress doc
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/faststore-config-options.mdx
  apps/site/pages/docs/faststore-config-options/custom-cypress-test.mdx
  apps/site/pages/docs/getting-started/3-project-structure.mdx
Labels: documentation

#2016 Docs: Update faststore-config-options.mdx
  apps/site/pages/docs/faststore-config-options.mdx
Labels: documentation

#2018 Docs: Fixes utilities import path
  apps/site/pages/docs/customizing/mixins-breakpoints.mdx
Labels: bug, documentation

#2019 Docs: review landing page
  apps/site/pages/index.mdx
Labels: documentation

#2034 Docs: Updates readme file - FastStore v2
  README.md
Labels: documentation
