Repository vtex/faststore, pull requests merged in 2023-08, with the labels that each got.

#1906 Fix: Search input is not being displayed on safari
  apps/site/pages/components/molecules/search-dropdown.mdx
  apps/site/pages/components/organisms/navbar.mdx
  packages/ui/src/components/molecules/SearchDropdown/styles.scss
  packages/ui/src/components/organisms/Navbar/styles.scss
Labels: bug

#1929 Docs: Add cypress extension
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/building-sections/component-customization-overview.mdx
  apps/site/pages/docs/building-sections/list-of-native-sections.mdx
  apps/site/pages/docs/building-sections/overriding-components-and-props.mdx
  apps/site/pages/docs/faststore-config-options/custom-cypress-test.mdx
Labels: documentation

#1885 Docs: Add Onboarding Dashboard guide and Glossary
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/getting-started-glossary.mdx
  apps/site/pages/docs/getting-started/1-faststore-onboarding/dashboard.mdx
Labels: documentation

#1881 Docs: Integrating with VTEX Headless CMS
  apps/site/pages/docs/_meta.json
  apps/site/pages/docs/building-sections/component-customization-overview.mdx
  apps/site/pages/docs/building-sections/creating-a-new-section.mdx
  apps/site/pages/docs/customizing/components.mdx
  apps/site/pages/docs/customizing/pages.mdx
  apps/site/pages/docs/getting-started-requirements.mdx
  apps/site/pages/docs/getting-started/2-setting-up-the-project.mdx
  apps/site/pages/docs/getting-started/4-faststore-cli.mdx
  apps/site/pages/docs/getting-started/5-next-steps.mdx
  apps/site/pages/docs/go-live/1-setting-up-vtex-account-for-faststore.mdx
  apps/site/pages/docs/go-live/2-configuring-external-dns.mdx
  apps/site/pages/docs/go-live/4-integrating-the-vtex-checkout.mdx
  apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
  apps/site/pages/docs/go-live/overview.mdx
  apps/site/pages/docs/headless-cms-integration/1-configuring-the-vtex-account.mdx
  apps/site/pages/docs/headless-cms-integration/2-setting-up-the-headless-cms.mdx
  apps/site/pages/docs/headless-cms-integration/3-adding-content-types-and-sections.mdx
  apps/site/pages/docs/headless-cms-integration/4-Promoting-your-changes.mdx
  apps/site/pages/docs/headless-cms-overview.mdx
  apps/site/pages/docs/headless-cms-troubleshooting/error-installing-headless-cms.mdx
  apps/site/pages/docs/icons.mdx
  apps/site/pages/docs/index.mdx
Labels: documentation

#1923 Doc: Update go-live step 5 for Legacy CMS stores
  apps/site/pages/docs/go-live/5-integrating-the-vtex-order-placed-and-my-account.mdx
Labels: documentation

#1957 fix: Improves `ProductTitle` Accessibility
  packages/components/src/molecules/ProductTitle/ProductTitle.tsx
Labels: enhancement

#1949 fix: SKU overflow in PDP
  packages/ui/src/components/molecules/SkuSelector/styles.scss
Labels: bug

#1950 fix: Nested footer elements
  packages/core/src/components/sections/Footer/Footer.tsx
Labels: bug

#1971 Docs: Fixes props description
  apps/site/pages/components/molecules/sku-selector.mdx
Labels: documentation
