Repository vtex/faststore, pull requests merged in 2024-11, with the labels that each got.

#2492 Feat: Improve Dropdown Component
  apps/site/middleware.ts
  apps/site/pages/components/molecules/dropdown.mdx
  packages/components/src/atoms/Button/index.ts
  packages/components/src/molecules/Dropdown/Dropdown.tsx
  packages/components/src/molecules/Dropdown/DropdownButton.tsx
  packages/components/src/molecules/Dropdown/DropdownItem.tsx
  packages/components/src/molecules/Dropdown/DropdownMenu.tsx
  packages/components/src/molecules/Dropdown/contexts/DropdownContext.ts
  packages/components/src/molecules/Dropdown/hooks/useDropdown.ts
  packages/components/src/molecules/Dropdown/hooks/useDropdownItem.ts
  packages/components/src/molecules/Dropdown/hooks/useDropdownPosition.ts
  packages/components/src/molecules/Dropdown/hooks/useDropdownTrigger.ts
Labels: contributing

#2535 fix: uncomment middleware
  apps/site/middleware.ts
Labels: documentation, hotfix

#2526 Chore: Fix CLS issues and Navbar dynamic imports
  packages/core/src/components/navigation/Navbar/Navbar.tsx
  packages/core/src/components/sections/Navbar/DefaultComponents.ts
  packages/core/src/components/sections/Navbar/section.module.scss
  packages/core/src/components/sections/RegionBar/RegionBar.tsx
Labels: performance

#2534 fix: NaN when string is inputed on quantity input
  packages/components/src/molecules/QuantitySelector/QuantitySelector.tsx
Labels: bug, contributing

#2538 Chore: Applies next/dynamic for Toast
  packages/core/src/components/cms/GlobalSections.tsx
  packages/core/src/components/cms/RenderSections.tsx
  packages/core/src/components/common/Toast/Toast.tsx
Labels: performance

#2541 fix: Revert Navbar isMobile changes
  packages/core/src/components/navigation/Navbar/Navbar.tsx
Labels: bug

#2550 Feat: Applies next/dynamic for SearchInput & adjustments
  packages/core/src/components/navigation/Navbar/Navbar.tsx
  packages/core/src/components/navigation/NavbarLinks/NavbarLinks.tsx
  packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx
  packages/core/src/components/search/SearchInput/SearchInput.tsx
Labels: performance

#2528 fix: Consider `shouldSplitItem` value from `ValidateCart` mutation response
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
  packages/api/src/typeDefs/cart.graphql
  packages/api/src/typeDefs/order.graphql
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/src/sdk/cart/index.ts
Labels: bug

#2552 feat: next/dynamic in `BannerText` internal components SFS-1518
  packages/core/src/components/sections/BannerText/DefaultComponents.ts
Labels: performance

#2553 feat: next/dynamic in `CartSidebar` internal components SFS-1517
  packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
Labels: performance

#2554 feat: split the global sections in own file
  packages/core/src/components/cms/global/Components.ts
Labels: performance

#2555 feat: split the homepage sections in own file
  packages/core/src/components/cms/home/Components.ts
Labels: performance, depends on

#2559 Feat: next/dynamic `ProductShelf` Section and internal components.
  packages/core/src/components/sections/ProductShelf/DefaultComponents.ts
  packages/core/src/components/ui/ProductShelf/ProductShelf.tsx
Labels: performance, depends on

#2571 fix: Support `releaseId` query string param for Headless CMS previews
  packages/core/src/pages/api/preview.ts
Labels: bug
