Repository vtex/faststore, pull requests merged in 2024-12, with the labels that each got.

#2503 feat: sku matrix ui and components
  packages/components/src/hooks/index.ts
  packages/components/src/hooks/useSKUMatrix.ts
  packages/components/src/index.ts
  packages/components/src/organisms/SKUMatrix/SKUMatrix.tsx
  packages/components/src/organisms/SKUMatrix/SKUMatrixSidebar.tsx
  packages/components/src/organisms/SKUMatrix/SKUMatrixTrigger.tsx
  packages/components/src/organisms/SKUMatrix/index.ts
  packages/components/src/organisms/SKUMatrix/provider/SKUMatrixProvider.tsx
  packages/ui/src/components/organisms/SKUMatrix/styles.scss
  packages/ui/src/styles/components.scss
Labels: enhancement, contributing

#2519 Feat: Add params sponsoredCount query search
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/search/index.ts
  packages/api/src/platforms/vtex/resolvers/query.ts
  packages/api/src/typeDefs/query.graphql
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/cms/faststore/sections.json
  packages/core/src/customizations/src/fragments/ClientManyProducts.ts
  packages/core/src/sdk/product/useLocalizedVariables.ts
  packages/core/src/sdk/product/usePageProductsQuery.ts
  packages/core/src/sdk/product/useProductsPrefetch.ts
  packages/core/src/sdk/product/useProductsQuery.ts
Labels: enhancement, contributing

#2504 feat: sku matrix packages api
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/resolvers/skuVariations.ts
  packages/api/src/typeDefs/skuVariants.graphql
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/src/sdk/product/useAllVariantProducts.ts
Labels: enhancement, contributing

#2585 fix: `Sentinel` rendering and wrong PLP's pagination behavior (#2585)
  packages/core/src/components/product/ProductGrid/ProductGrid.tsx
  packages/core/src/components/ui/ProductGallery/ProductGalleryPage.tsx
  packages/core/src/sdk/search/Sentinel.tsx
Labels: bug

#2505 feat: sku matrix packages core
  packages/core/cms/faststore/sections.json
  packages/core/src/components/sections/ProductDetails/DefaultComponents.ts
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/sections/ProductDetails/section.module.scss
  packages/core/src/components/ui/SKUMatrix/SKUMatrixSidebar.tsx
  packages/core/src/sdk/cart/useBuyButton.ts
  packages/core/src/typings/overrides.ts
Labels: enhancement, depends on, contributing

#2587 docs: updates pull request template and updates contributing file
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.MD
  packages/core/README.md
  packages/core/pull_request_template.md
Labels: documentation

#2596 feat: `Filter` with next/dynamic and lazy import
  packages/core/src/components/search/Filter/Filter.tsx
  packages/core/src/components/search/Filter/FilterDesktop.tsx
  packages/core/src/components/search/Filter/FilterSlider.tsx
  packages/core/src/components/search/Filter/index.ts
  packages/core/src/components/sections/ProductGallery/DefaultComponents.ts
  packages/core/src/components/ui/ProductGallery/ProductGallery.tsx
Labels: performance

#2567 feat: handle RC Events
  packages/core/src/Layout.tsx
  packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts
  packages/core/src/sdk/analytics/platform/vtex/index.ts
  packages/core/src/sdk/analytics/platform/vtex/rc.ts
  packages/core/src/sdk/analytics/platform/vtex/search.ts
  packages/core/src/sdk/analytics/types.ts
  packages/sdk/src/analytics/events/page_view.ts
Labels: enhancement
