Repository vtex/faststore, pull requests merged in 2024-10, with the labels that each got.

#2438 Add showSponsored as api configuration on faststore.config.js to IntelligentSearch integration
  packages/api/local/server.ts
  packages/api/mocks/AllProductsQuery.ts
  packages/api/mocks/ProductQuery.ts
  packages/api/mocks/RedirectQuery.ts
  packages/api/mocks/SearchQuery.ts
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/search/index.ts
  packages/api/src/platforms/vtex/clients/search/types/ProductSearchResult.ts
  packages/api/src/platforms/vtex/index.ts
  packages/api/src/platforms/vtex/resolvers/product.ts
  packages/api/src/typeDefs/advertisement.graphql
  packages/api/src/typeDefs/product.graphql
  packages/api/test/queries.test.ts
  packages/api/test/schema.test.ts
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/faststore.config.default.js
  packages/core/src/components/product/ProductCard/ProductCard.tsx
  packages/core/src/server/options.ts
Labels: enhancement, contributing

#2462 feat: Adds B2B Customer ID
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/clients/commerce/types/Session.ts
  packages/api/src/platforms/vtex/resolvers/validateSession.ts
  packages/api/src/typeDefs/session.graphql
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/discovery.config.default.js
  packages/core/src/sdk/session/index.ts
  packages/sdk/src/session/index.ts
  packages/sdk/test/session/index.test.tsx
Labels: contributing

#2490 fix(api): slugify breaking category with pipe in its name
  packages/api/src/platforms/vtex/utils/slugify.ts
Labels: bug

#2481 Chore: Removes `BannerNewsletter` section from home
  packages/core/src/pages/index.tsx
Labels: performance

#2496 Fix: codegen dependencies
  packages/core/package.json
  yarn.lock
Labels: hotfix

#2472 Feat: import `sendAnalyticsEvent` on demand
  packages/core/src/components/cart/CartItem/CartItem.tsx
  packages/core/src/components/cart/CartSidebar/CartSidebar.tsx
  packages/core/src/components/search/SearchInput/SearchInput.tsx
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts
  packages/core/src/sdk/analytics/hooks/useViewItemListEvent.ts
  packages/core/src/sdk/cart/useBuyButton.ts
  packages/core/src/sdk/cart/useRemoveButton.ts
  packages/core/src/sdk/product/useProductGalleryQuery.ts
  packages/core/src/sdk/product/useProductLink.ts
  packages/core/src/sdk/search/useSuggestions.ts
Labels: performance

#2491 chore: adjust CLI to meet FSP Spec
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/dev.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/utils/directory.test.ts
  packages/cli/src/utils/directory.ts
Labels: contributing

#2480 chore: Migrate envelop core to v5
  packages/api/package.json
  packages/core/package.json
  yarn.lock
Labels: performance

#2498 Feat: Adds intersection (ViewportObserver) component
  packages/core/src/components/cms/ViewportObserver.tsx
  packages/core/src/components/product/ProductGrid/ProductGrid.tsx
  packages/core/src/components/ui/ProductGallery/ProductGallery.tsx
  packages/core/src/components/ui/ProductGallery/ProductGalleryPage.tsx
Labels: performance

#2497 feat: enable preact experimental feature
  packages/cli/package.json
  packages/cli/src/utils/dependencies.ts
  packages/cli/src/utils/generate.ts
  packages/core/discovery.config.default.js
  packages/core/next.config.js
  yarn.lock
Labels: performance

#2487 feat: Add `useScreenResize` hook (SFS-1509)
  packages/core/src/components/common/Footer/FooterLinks.tsx
  packages/core/src/components/navigation/Navbar/Navbar.tsx
  packages/core/src/components/search/Filter/Filter.tsx
  packages/core/src/components/sections/RegionBar/RegionBar.tsx
  packages/core/src/components/ui/Carousel/Carousel.tsx
  packages/core/src/sdk/ui/useScreenResize.ts
Labels: performance

#2500 Enable monorepo build on Vercel
  packages/cli/src/commands/build.ts
  packages/cli/src/utils/generate.ts
  packages/core/next.config.js
Labels: don't merge, WIP

#2516 Decrease FastStore CLI verbosity
  packages/cli/src/commands/dev.ts
  packages/cli/src/commands/generate-graphql.ts
  packages/cli/src/utils/dependencies.ts
  packages/cli/src/utils/generate.ts
  packages/cli/src/utils/logger.ts
  packages/cli/src/utils/runCommandSync.ts
  turbo.json
Labels: contributing

#2524 fix: has child items logic on validate cart (bug)
  packages/api/src/platforms/vtex/resolvers/validateCart.ts
Labels: contributing
