Repository vtex/faststore, pull requests merged in 2024-09, with the labels that each got.

#2398 Feat: Adds Card Component
  apps/site/pages/components/molecules/card.mdx
  packages/components/src/index.ts
  packages/components/src/molecules/Card/Card.tsx
  packages/components/src/molecules/Card/index.ts
  packages/ui/src/components/molecules/Card/styles.scss
  packages/ui/src/styles/components.scss
Labels: ui-molecule

#2442 Fix: Custom theme import priority
  packages/core/src/pages/_app.tsx
Labels: bug, contributing

#2440 Feat: Adds jest-axe and Card component test
  apps/site/pages/components/molecules/card.mdx
  packages/components/jest.config.js
  packages/components/jest.setup.ts
  packages/components/package.json
  packages/components/test/molecules/Card/Card.test.tsx
  packages/components/test/molecules/CheckboxField/CheckboxField.test.tsx
  packages/components/tsconfig.json
  yarn.lock
Labels: enhancement

#2455 Fix: v2 api build
  packages/api/package.json
  packages/api/src/typeDefs/index.ts
  packages/components/package.json
  packages/core/package.json
  packages/ui/package.json
Labels: hotfix

#2394 feat: trigger critical events for analytics
  packages/core/src/Layout.tsx
  packages/core/src/sdk/analytics/hooks/usePageViewEvent.ts
  packages/sdk/src/analytics/events/page_view.ts
  packages/sdk/src/analytics/wrap.ts
  packages/sdk/src/index.ts
Labels: contributing

#2405 feat: Adds B2B Customer ID
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/clients/commerce/types/Session.ts
  packages/api/src/platforms/vtex/resolvers/validateSession.ts
  packages/api/src/typeDefs/session.graphql
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/faststore.config.default.js
  packages/core/src/sdk/session/index.ts
  packages/sdk/src/session/index.ts
  packages/sdk/test/session/index.test.tsx
Labels: enhancement, contributing

#2459 Revert "feat: Adds B2B Customer ID"
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/clients/commerce/types/Session.ts
  packages/api/src/platforms/vtex/resolvers/validateSession.ts
  packages/api/src/typeDefs/session.graphql
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/faststore.config.default.js
  packages/core/src/sdk/session/index.ts
  packages/sdk/src/session/index.ts
  packages/sdk/test/session/index.test.tsx
Labels: hotfix

#2425 Feat: Migrating from next/head to built in SEO (metadata)
  packages/core/app/fs-next-update/page.tsx
Labels: Next 13

#2445 docs: update version on readme
  README.md
Labels: documentation

#2470 Feat: adds new `deviceSizes` and adjust `Hero` Image
  packages/core/next.config.js
  packages/core/src/components/sections/Hero/Hero.tsx
Labels: performance

#2468 feat: removes lazy without suspense from global sections
  packages/core/src/components/cms/GlobalSections.tsx
Labels: performance

#2469 feat: removes nextjs-progressbar and chalk
  packages/core/package.json
  packages/core/src/components/cms/RenderSections.tsx
  packages/core/src/pages/_app.tsx
  yarn.lock
Labels: performance

#2471 Feat: `Promise.all` homepage and global Promises
  packages/core/src/components/cms/GlobalSections.tsx
  packages/core/src/pages/index.tsx
Labels: performance

#2458 Fix: Integration and enable back accessibility tests
  packages/components/src/organisms/PaymentMethods/PaymentMethods.tsx
  packages/core/cypress/integration/a11y.test.js
  packages/core/cypress/integration/analytics.test.js
  packages/core/cypress/integration/seo.test.js
  packages/core/faststore.config.default.js
  packages/core/src/components/common/Footer/Footer.tsx
  packages/core/src/components/common/Footer/FooterLinks.tsx
  packages/core/src/components/common/Footer/FooterSocial.tsx
  packages/core/src/components/sections/Incentives/Incentives.tsx
  packages/core/src/components/ui/Incentives/Incentives.tsx
  packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx
  packages/ui/src/components/atoms/Incentive/Incentive.tsx
  turbo.json
Labels: bug, enhancement

#2476 Chore: Updates FastStore Contributing Guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.MD
  README.md
Labels: documentation

#2478 chore: removes mark from components/sections
  packages/core/cypress/integration/performance.test.js
  packages/core/src/components/common/Alert/Alert.tsx
  packages/core/src/components/common/Footer/Footer.tsx
  packages/core/src/components/navigation/Navbar/Navbar.tsx
  packages/core/src/components/navigation/NavbarLinks/NavbarLinks.tsx
  packages/core/src/components/navigation/NavbarSlider/NavbarSlider.tsx
  packages/core/src/components/sections/ProductGallery/ProductGallery.tsx
  packages/core/src/pages/[...slug].tsx
  packages/core/src/pages/[slug]/p.tsx
  packages/core/src/pages/index.tsx
  packages/core/src/pages/s.tsx
  packages/core/src/sdk/tests/mark.tsx
Labels: performance

#2477 Feat: adds preconnect and dns-prefetch
  packages/core/src/pages/_document.tsx
Labels: performance
