Repository vtex/faststore, pull requests merged in 2025-02, with the labels that each got.

#2546 feat: quick order settings
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/cms/faststore/sections.json
  packages/core/src/components/navigation/Navbar/Navbar.tsx
  packages/core/src/components/product/ProductCard/ProductCard.tsx
  packages/core/src/components/search/SearchDropdown/SearchDropdown.tsx
  packages/core/src/components/search/SearchInput/SearchInput.tsx
  packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
  packages/core/src/components/sections/Navbar/Navbar.tsx
Labels: enhancement, contributing

#2635 feat: adjust rating styles
  packages/components/src/molecules/Rating/Rating.tsx
  packages/ui/src/components/molecules/Rating/styles.scss
Labels: enhancement

#2649 feat: reviews query resolver
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/clients/commerce/types/ProductReview.ts
  packages/api/src/platforms/vtex/resolvers/query.ts
  packages/api/src/typeDefs/productReview.graphql
  packages/api/src/typeDefs/query.graphql
  packages/api/test/schema.test.ts
  packages/core/test/server/index.test.ts
Labels: depends on

#2638 feat: add checkbox field error variant
  packages/components/src/molecules/CheckboxField/CheckboxField.tsx
  packages/ui/src/components/molecules/CheckboxField/styles.scss
Labels: enhancement

#2650 feat: reviews mutation resolver
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/errors.ts
  packages/api/src/platforms/vtex/clients/commerce/index.ts
  packages/api/src/platforms/vtex/resolvers/createProductReview.ts
  packages/api/src/platforms/vtex/resolvers/mutation.ts
  packages/api/src/platforms/vtex/utils/cookies.ts
  packages/api/src/typeDefs/mutation.graphql
  packages/api/src/typeDefs/productReview.graphql
  packages/api/test/schema.test.ts
  packages/core/test/server/index.test.ts
Labels: depends on

#2636 feat: add rating field
  packages/components/src/index.ts
  packages/components/src/molecules/RatingField/RatingField.tsx
  packages/components/src/molecules/RatingField/index.ts
  packages/ui/src/components/molecules/Rating/styles.scss
  packages/ui/src/components/molecules/RatingField/styles.scss
  packages/ui/src/styles/components.scss
Labels: enhancement, depends on

#2663 feat: create review and ratings section structure
  packages/core/cms/faststore/sections.json
  packages/core/index.ts
  packages/core/src/components/sections/ReviewsAndRatings/DefaultComponents.ts
  packages/core/src/components/sections/ReviewsAndRatings/OverriddenDefaultReviewsAndRatings.ts
  packages/core/src/components/sections/ReviewsAndRatings/ReviewsAndRatings.tsx
  packages/core/src/components/sections/ReviewsAndRatings/index.tsx
  packages/core/src/components/sections/ReviewsAndRatings/section.module.scss
  packages/core/src/components/ui/ReviewsAndRatings/ReviewsAndRatings.tsx
  packages/core/src/components/ui/ReviewsAndRatings/index.ts
  packages/core/src/customizations/src/components/overrides/ReviewsAndRatings.tsx
  packages/core/src/pages/[slug]/p.tsx
  packages/core/src/plugins/overrides/ReviewsAndRatings.tsx
  packages/core/src/typings/overrides.ts
Labels: enhancement

#2640 feat: create textarea component
  packages/components/src/atoms/Textarea/Textarea.tsx
  packages/components/src/atoms/Textarea/index.ts
  packages/components/src/index.ts
  packages/ui/src/components/atoms/TextArea/TextArea.tsx
  packages/ui/src/components/atoms/TextArea/index.ts
  packages/ui/src/components/atoms/Textarea/styles.scss
  packages/ui/src/index.ts
  packages/ui/src/styles/components.scss
Labels: enhancement

#2672 feat: create modal footer compound component
  packages/components/src/index.ts
  packages/components/src/molecules/Modal/ModalFooter.tsx
  packages/components/src/molecules/Modal/index.tsx
  packages/ui/src/components/molecules/Modal/styles.scss
Labels: enhancement

#2644 feat: add tooltip component
  packages/components/src/index.ts
  packages/components/src/molecules/Tooltip/Tooltip.tsx
  packages/components/src/molecules/Tooltip/index.ts
  packages/ui/src/components/molecules/Tooltip/styles.scss
  packages/ui/src/styles/components.scss
Labels: enhancement

#2641 feat: add textareafield component
  packages/components/src/index.ts
  packages/components/src/molecules/TextareaField/TextareaField.tsx
  packages/components/src/molecules/TextareaField/index.ts
  packages/ui/src/components/molecules/TextareaField/styles.scss
  packages/ui/src/styles/components.scss
Labels: enhancement, depends on

#2645 feat: add review card
  packages/components/src/index.ts
  packages/components/src/molecules/ReviewCard/ReviewCard.tsx
  packages/components/src/molecules/ReviewCard/ReviewCardAuthor.tsx
  packages/components/src/molecules/ReviewCard/ReviewCardDate.tsx
  packages/components/src/molecules/ReviewCard/index.ts
  packages/components/src/utils/date.ts
  packages/storybook/.storybook/main.js
  packages/storybook/public/icons.svg
  packages/storybook/stories/review-card.stories.tsx
  packages/ui/src/components/molecules/ReviewCard/styles.scss
  packages/ui/src/styles/components.scss
Labels: enhancement, depends on

#2543 feat: search product item control
  packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
  packages/ui/src/components/molecules/SearchProducts/styles.scss
Labels: enhancement, contributing

#2694 feat: Add `category`, `mainEntityOfPage` and `@id` to Product structured data
  packages/core/cms/faststore/content-types.json
  packages/core/src/pages/[slug]/p.tsx
  packages/core/src/server/cms/pdp.ts
Labels: enhancement
