Repository vtex/faststore, pull requests merged in 2025-03, with the labels that each got.

#2712 fix: Product Details' Buy Button excessive state reset
  packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx
Labels: bug

#2710 fix: ClientShippingSimulationQuery being called multiple times
  packages/core/src/sdk/shipping/useShippingSimulation.ts
Labels: bug

#2711 fix: Do not include similar categories in the breadcrumb list
  packages/api/src/platforms/vtex/resolvers/product.ts
Labels: bug

#2714 fix: Breadcrumb display and it style
  packages/core/src/components/sections/Breadcrumb/section.module.scss
  packages/core/src/components/sections/Navbar/section.module.scss
  packages/core/src/styles/global/index.scss
  packages/ui/src/components/molecules/Dropdown/styles.scss
  packages/ui/src/components/organisms/Navbar/styles.scss
Labels: bug

#2708 feat: [Delivery Promise] Default postal code
  packages/core/discovery.config.default.js
  packages/core/src/sdk/session/index.ts
Labels: enhancement

#2547 feat: search product control implementations
  packages/components/src/molecules/SearchProducts/SearchProductItemContent.tsx
  packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
  packages/core/src/components/search/SearchInput/SearchInput.tsx
  packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
  packages/core/src/components/sections/Navbar/section.module.scss
  packages/core/src/sdk/cart/useBuyButton.ts
  packages/ui/src/components/molecules/SearchProducts/styles.scss
Labels: enhancement, depends on

#2715 fix: override to use core breadcrumb component
  packages/core/src/components/sections/Breadcrumb/Breadcrumb.tsx
  packages/core/src/components/sections/Breadcrumb/DefaultComponents.ts
  packages/core/src/components/ui/Breadcrumb/Breadcrumb.tsx
  packages/core/src/typings/overrides.ts
Labels: bug

#2732 fix: Prevent whitespaces in Search page's `canonical`
  packages/core/src/pages/s.tsx
Labels: bug

#2740 fix: pass cookies to intelligent search requests
  packages/api/src/platforms/vtex/clients/search/index.ts
  packages/api/test/mocks/AllProductsQuery.ts
  packages/api/test/mocks/ProductQuery.ts
  packages/api/test/mocks/RedirectQuery.ts
  packages/api/test/mocks/SearchQuery.ts
  packages/api/test/mocks/ValidateCartMutation.ts
Labels: bug

#2664 feat: Add plugins apis support
  packages/cli/src/utils/directory.ts
  packages/cli/src/utils/plugins.ts
Labels: enhancement
