Repository vtex/faststore, pull requests merged in 2025-01, with the labels that each got.

#2611 feat: Dynamically import `BreadcrumbBase` internal components
  packages/components/src/molecules/Breadcrumb/BreadcrumbBase.tsx
Labels: performance

#2588 feat: adds SKUMatrix component
  packages/api/src/__generated__/schema.ts
  packages/api/src/platforms/vtex/resolvers/skuVariations.ts
  packages/api/src/typeDefs/skuVariants.graphql
  packages/components/src/hooks/index.ts
  packages/components/src/hooks/useSKUMatrix.ts
  packages/components/src/index.ts
  packages/components/src/organisms/SKUMatrix/SKUMatrix.tsx
  packages/components/src/organisms/SKUMatrix/SKUMatrixSidebar.tsx
  packages/components/src/organisms/SKUMatrix/SKUMatrixTrigger.tsx
  packages/components/src/organisms/SKUMatrix/index.ts
  packages/components/src/organisms/SKUMatrix/provider/SKUMatrixProvider.tsx
  packages/core/@generated/gql.ts
  packages/core/@generated/graphql.ts
  packages/core/cms/faststore/sections.json
  packages/core/src/components/sections/ProductDetails/DefaultComponents.ts
  packages/core/src/components/sections/ProductDetails/ProductDetails.tsx
  packages/core/src/components/sections/ProductDetails/section.module.scss
  packages/core/src/components/ui/SKUMatrix/SKUMatrixSidebar.tsx
  packages/core/src/sdk/cart/useBuyButton.ts
  packages/core/src/sdk/product/useAllVariantProducts.ts
  packages/core/src/typings/overrides.ts
  packages/ui/src/components/organisms/SKUMatrix/styles.scss
  packages/ui/src/styles/components.scss
Labels: contributing

#2563 feat: Adds Plugins feature
  packages/cli/src/utils/directory.ts
  packages/cli/src/utils/generate.ts
  packages/cli/src/utils/hcms.ts
  packages/cli/src/utils/plugins.ts
  packages/core/src/components/cms/global/Components.ts
  packages/core/src/components/cms/home/Components.ts
  packages/core/src/components/cms/plp/Components.ts
  packages/core/src/components/cms/search/Components.ts
  packages/core/src/components/sections/Alert/OverriddenDefaultAlert.ts
  packages/core/src/components/sections/BannerText/OverriddenDefaultBannerText.ts
  packages/core/src/components/sections/Breadcrumb/OverriddenDefaultBreadcrumb.ts
  packages/core/src/components/sections/CrossSellingShelf/OverriddenDefaultCrossSellingShelf.ts
  packages/core/src/components/sections/EmptyState/OverriddenDefaultEmptyState.ts
  packages/core/src/components/sections/Hero/OverriddenDefaultHero.ts
  packages/core/src/components/sections/Navbar/OverriddenDefaultNavbar.ts
  packages/core/src/components/sections/Newsletter/OverriddenDefaultNewsletter.ts
  packages/core/src/components/sections/ProductDetails/OverriddenDefaultProductDetails.ts
  packages/core/src/components/sections/ProductGallery/OverriddenDefaultProductGallery.ts
  packages/core/src/components/sections/ProductShelf/OverriddenDefaultProductShelf.ts
  packages/core/src/components/sections/RegionBar/OverriddenDefaultRegionBar.ts
  packages/core/src/components/templates/LandingPage/LandingPage.tsx
  packages/core/src/customizations/src/GlobalOverrides.tsx
  packages/core/src/pages/404.tsx
  packages/core/src/pages/500.tsx
  packages/core/src/pages/[slug]/p.tsx
  packages/core/src/pages/_app.tsx
  packages/core/src/pages/login.tsx
  packages/core/src/plugins/.gitkeep
  packages/core/src/plugins/index.scss
  packages/core/src/plugins/index.ts
  packages/core/src/plugins/overrides/Alert.tsx
  packages/core/src/plugins/overrides/BannerText.tsx
  packages/core/src/plugins/overrides/Breadcrumb.tsx
  packages/core/src/plugins/overrides/CrossSellingShelf.tsx
  packages/core/src/plugins/overrides/EmptyState.tsx
  packages/core/src/plugins/overrides/Hero.tsx
  packages/core/src/plugins/overrides/Navbar.tsx
  packages/core/src/plugins/overrides/Newsletter.tsx
  packages/core/src/plugins/overrides/ProductDetails.tsx
  packages/core/src/plugins/overrides/ProductGallery.tsx
  packages/core/src/plugins/overrides/ProductShelf.tsx
  packages/core/src/plugins/overrides/RegionBar.tsx
  packages/core/src/plugins/overrides/ThirdPartyScripts.tsx
  packages/core/src/plugins/overrides/WebFonts.tsx
Labels: enhancement, contributing

#2642 fix(sdk): safari rendering
  packages/core/src/sdk/performance/useTTI.ts
Labels: bug

#2654 feat: enable lazy loading skip on custom sections
  packages/core/src/components/cms/RenderSections.tsx
  packages/core/src/components/cms/ViewportObserver.tsx
Labels: enhancement
