Repository vtex/faststore, pull requests merged in 2025-05, with the labels that each got.

#2811 fix: Sets domain search cookies
  packages/core/src/sdk/analytics/platform/vtex/search.ts
  packages/core/src/utils/getBaseDomain.ts
Labels: bug

#2807 feat: [CP-432] [CP-433] Adding CP integration as a data source alternative to hCMS
  packages/core/discovery.config.default.js
  packages/core/package.json
  packages/core/src/components/cms/GlobalSections.tsx
  packages/core/src/components/templates/LandingPage/LandingPage.tsx
  packages/core/src/components/templates/ProductListingPage/ProductListing.tsx
  packages/core/src/experimental/searchServerSideFunctions/getServerSideProps.ts
  packages/core/src/experimental/searchServerSideFunctions/getStaticProps.ts
  packages/core/src/pages/404.tsx
  packages/core/src/pages/500.tsx
  packages/core/src/pages/[...slug].tsx
  packages/core/src/pages/[slug]/p.tsx
  packages/core/src/pages/api/preview.ts
  packages/core/src/pages/index.tsx
  packages/core/src/pages/login.tsx
  packages/core/src/sdk/error/MissingContentError/MissingContentError.ts
  packages/core/src/sdk/error/MultipleContentError/MultipleContentError.ts
  packages/core/src/server/cms/index.ts
  packages/core/src/server/content/service.ts
  packages/core/src/server/content/types.ts
  packages/core/src/server/content/utils.ts
  pnpm-lock.yaml
Labels: enhancement

#2837 feat: selected tags and clear all
  packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrders.tsx
  packages/core/src/components/account/orders/MyAccountListOrders/MyAccountListOrdersTable/styles.scss
  packages/core/src/components/account/orders/MyAccountListOrders/MyAccountSelectedTags/MyAccountSelectedTags.tsx
  packages/core/src/components/account/orders/MyAccountListOrders/MyAccountSelectedTags/index.ts
  packages/core/src/components/account/orders/MyAccountListOrders/MyAccountSelectedTags/styles.scss
  packages/core/src/components/account/orders/MyAccountListOrders/styles.module.scss
Labels: depends on

#2844 fix: discovery config import
  packages/core/src/sdk/error/MissingContentError/MissingContentError.ts
  packages/core/src/sdk/error/MultipleContentError/MultipleContentError.ts
Labels: bug

#2852 chore: Pickup All config
  packages/core/cms/faststore/content-types.json
  packages/core/cms/faststore/sections.json
  packages/core/src/components/search/Filter/FilterDeliveryOption.tsx
  packages/core/src/components/search/Filter/FilterDesktop.tsx
  packages/core/src/components/search/Filter/FilterSlider.tsx
  packages/core/src/utils/globalSettings.ts
Labels: enhancement

#2851 feat: Add Region Slider to set/change location
  packages/components/src/hooks/UIProvider.tsx
  packages/components/src/hooks/index.ts
  packages/components/src/organisms/Filter/FilterSlider.tsx
  packages/core/cms/faststore/content-types.json
  packages/core/cms/faststore/sections.json
  packages/core/src/components/region/RegionSlider/RegionSlider.tsx
  packages/core/src/components/region/RegionSlider/index.ts
  packages/core/src/components/region/RegionSlider/section.module.scss
  packages/core/src/components/search/Filter/FilterDeliveryOption.tsx
  packages/core/src/components/search/Filter/FilterDesktop.tsx
  packages/core/src/components/search/Filter/FilterSlider.tsx
  packages/core/src/utils/globalSettings.ts
  packages/ui/src/components/organisms/FilterSlider/styles.scss
Labels: enhancement

#2868 fix: theme styles import
  packages/cli/src/utils/generate.ts
  packages/core/src/pages/_app.tsx
  packages/core/src/styles/main.scss
Labels: bug
