Repository vtex/faststore, pull requests merged in 2025-04, with the labels that each got.

#2757 fix: Encode redirect destination
  packages/core/src/sdk/redirects/index.ts
Labels: bug

#2791 feat: explicitly add allowRedirect to IS req
  packages/api/src/platforms/vtex/clients/search/index.ts
  packages/api/src/platforms/vtex/resolvers/query.ts
  packages/api/test/mocks/AllProductsQuery.ts
  packages/api/test/mocks/ProductQuery.ts
  packages/api/test/mocks/RedirectQuery.ts
  packages/api/test/mocks/SearchQuery.ts
  packages/api/test/mocks/ValidateCartMutation.ts
Labels: bug, enhancement

#2614 feat: controlled checkbox field
  packages/components/src/molecules/CheckboxField/CheckboxField.tsx
  packages/ui/src/components/organisms/SKUMatrix/styles.scss
Labels: contributing

#2798 chore: export usePageProductsQuery hooks
  packages/core/src/experimental/index.ts
Labels: enhancement
